In [116]:
import pandas as pd
import numpy as np
from ycimpute.imputer import iterforest

In [117]:
file = 'test_clean.csv'
df = pd.read_csv(file)
df.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0,1461,20,1.0,80.0,11622,1,1,1,1.0,...,0,0,0,120,0,0,6,2010,1.0,1
1,1,1462,20,2.0,81.0,14267,1,2,1,1.0,...,36,0,0,0,0,12500,6,2010,1.0,1
2,2,1463,60,2.0,74.0,13830,1,2,1,1.0,...,34,0,0,0,0,0,3,2010,1.0,1
3,3,1464,60,2.0,78.0,9978,1,2,1,1.0,...,36,0,0,0,0,0,6,2010,1.0,1
4,4,1465,120,2.0,43.0,5005,1,2,4,1.0,...,82,0,0,144,0,0,1,2010,1.0,1

In [118]:
df.drop(labels=['Id', 'Unnamed: 0', 'FireplaceQu'], axis=1, inplace=True)

In [119]:
df_copy = df.copy()

In [120]:
no_missingdata = df_copy.columns[(df_copy.isnull().any() != True)].tolist()
no_missingdata

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition']

In [121]:
missingdata = df_copy.columns[df_copy.isnull().any()].tolist()
missingdata

['MSZoning',
 'LotFrontage',
 'Utilities',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'KitchenQual',
 'Functional',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'SaleType']

In [122]:
len(missingdata)

28

In [296]:
df_copy[missingdata]

,MSZoning,LotFrontage,Utilities,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,...,KitchenQual,Functional,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,SaleType
0,1.0,80.0,1.0,1.0,1.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,1.0,51.0,2.0,1.0,730.0,1.0,1.0,1.0
1,2.0,81.0,1.0,3.0,6.0,1.0,108.0,2.0,1.0,1.0,...,1.0,1.0,1.0,19.0,2.0,1.0,312.0,1.0,1.0,1.0
2,2.0,74.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,...,2.0,1.0,1.0,34.0,3.0,2.0,482.0,1.0,1.0,1.0
3,2.0,78.0,1.0,1.0,1.0,1.0,20.0,2.0,1.0,1.0,...,1.0,1.0,1.0,4.0,3.0,2.0,470.0,1.0,1.0,1.0
4,2.0,43.0,1.0,4.0,4.0,2.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,79.0,1.0,2.0,506.0,1.0,1.0,1.0
5,2.0,75.0,1.0,4.0,4.0,2.0,0.0,1.0,1.0,1.0,...,2.0,1.0,1.0,6.0,3.0,2.0,440.0,1.0,1.0,1.0
6,2.0,65.0,1.0,4.0,4.0,2.0,0.0,1.0,1.0,1.0,...,2.0,1.0,1.0,79.0,3.0,2.0,420.0,1.0,1.0,1.0
7,2.0,63.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,...,2.0,1.0,1.0,4.0,3.0,2.0,393.0,1.0,1.0,1.0
8,2.0,85.0,1.0,4.0,4.0,2.0,0.0,1.0,1.0,2.0,...,1.0,1.0,1.0,41.0,2.0,2.0,506.0,1.0,1.0,1.0
9,2.0,70.0,1.0,8.0,5.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,1.0,17.0,3.0,2.0,525.0,1.0,1.0,1.0
10,1.0,26.0,1.0,2.0,2.0,2.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,39.0,3.0,2.0,511.0,1.0,1.0,1.0
11,3.0,21.0,1.0,4.0,4.0,1.0,504.0,2.0,1.0,1.0,...,2.0,1.0,2.0,59.0,2.0,1.0,264.0,1.0,1.0,3.0
12,3.0,21.0,1.0,4.0,4.0,1.0,492.0,2.0,1.0,1.0,...,2.0,1.0,2.0,34.0,2.0,1.0,320.0,1.0,1.0,1.0
13,2.0,24.0,1.0,8.0,11.0,2.0,0.0,2.0,1.0,1.0,...,1.0,1.0,1.0,58.0,2.0,2.0,440.0,1.0,1.0,1.0
14,2.0,24.0,1.0,8.0,11.0,2.0,0.0,1.0,1.0,1.0,...,2.0,1.0,1.0,58.0,2.0,1.0,308.0,1.0,1.0,1.0
15,2.0,102.0,1.0,1.0,1.0,3.0,162.0,3.0,1.0,1.0,...,3.0,1.0,1.0,49.0,3.0,3.0,751.0,1.0,1.0,2.0
16,2.0,94.0,1.0,1.0,1.0,3.0,256.0,1.0,1.0,1.0,...,1.0,1.0,1.0,49.0,1.0,3.0,868.0,1.0,1.0,2.0
17,2.0,90.0,1.0,1.0,1.0,1.0,615.0,3.0,1.0,1.0,...,3.0,1.0,1.0,12.0,3.0,3.0,730.0,1.0,1.0,1.0
18,2.0,79.0,1.0,7.0,7.0,1.0,240.0,3.0,1.0,1.0,...,3.0,1.0,1.0,12.0,1.0,3.0,678.0,1.0,1.0,1.0
19,2.0,110.0,1.0,1.0,1.0,1.0,1095.0,3.0,1.0,2.0,...,3.0,1.0,1.0,1.0,3.0,3.0,958.0,1.0,1.0,1.0
20,2.0,105.0,1.0,1.0,1.0,1.0,232.0,1.0,1.0,2.0,...,1.0,1.0,1.0,21.0,3.0,3.0,756.0,1.0,1.0,1.0
21,2.0,41.0,1.0,1.0,1.0,3.0,178.0,1.0,1.0,3.0,...,1.0,1.0,1.0,14.0,1.0,2.0,484.0,1.0,1.0,1.0
22,2.0,100.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,12.0,3.0,2.0,430.0,1.0,1.0,1.0
23,2.0,43.0,1.0,1.0,1.0,1.0,14.0,1.0,1.0,4.0,...,1.0,1.0,1.0,14.0,3.0,2.0,437.0,1.0,1.0,1.0
24,2.0,67.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,...,1.0,1.0,3.0,7.0,3.0,2.0,400.0,1.0,1.0,1.0
25,2.0,63.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,...,1.0,1.0,3.0,7.0,3.0,2.0,433.0,1.0,1.0,1.0
26,2.0,60.0,1.0,1.0,1.0,1.0,114.0,3.0,1.0,1.0,...,1.0,1.0,1.0,4.0,3.0,3.0,962.0,1.0,1.0,1.0
27,2.0,73.0,1.0,1.0,1.0,1.0,226.0,1.0,1.0,5.0,...,1.0,1.0,1.0,12.0,1.0,3.0,880.0,1.0,1.0,1.0
28,4.0,92.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,49.0,1.0,2.0,676.0,1.0,1.0,2.0
29,4.0,84.0,1.0,1.0,1.0,2.0,0.0,3.0,1.0,1.0,...,1.0,1.0,1.0,12.0,3.0,2.0,528.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,3.0,50.0,1.0,2.0,2.0,2.0,0.0,2.0,1.0,1.0,...,4.0,1.0,2.0,80.0,2.0,1.0,272.0,1.0,1.0,1.0
1430,3.0,75.0,1.0,2.0,2.0,1.0,327.0,2.0,1.0,1.0,...,1.0,1.0,2.0,25.0,2.0,1.0,384.0,1.0,1.0,1.0
1431,5.0,69.0,1.0,3.0,6.0,2.0,0.0,5.0,5.0,5.0,...,2.0,5.0,7.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0
1432,5.0,50.0,1.0,6.0,3.0,2.0,0.0,2.0,1.0,3.0,...,2.0,4.0,7.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0
1433,5.0,60.0,1.0,2.0,2.0,2.0,0.0,4.0,3.0,1.0,...,2.0,1.0,7.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0
1434,3.0,41.0,1.0,7.0,7.0,3.0,473.0,3.0,1.0,2.0,...,3.0,1.0,1.0,12.0,3.0,2.0,495.0,1.0,1.0,2.0
1435,3.0,44.0,1.0,7.0,7.0,3.0,186.0,3.0,1.0,2.0,...,1.0,1.0,1.0,7.0,3.0,2.0,525.0,1.0,1.0,1.0
1436,2.0,69.0,1.0,8.0,5.0,2.0,0.0,1.0,1.0,2.0,...,4.0,1.0,1.0,54.0,3.0,2.0,576.0,1.0,1.0,1.0
1437,2.0,65.0,1.0,8.0,5.0,2.0,0.0,2.0,1.0,3.0,...,2.0,1.0,6.0,77.0,2.0,2.0,616.0,1.0,1.0,1.0
1438,2.0,70.0,1.0,1.0,1.0,2.0,0.0,3.0,1.0,1.0,...,1.0,1.0,1.0,3.0,1.0,2.0,490.0,1.0,1.0,1.0
1439,2.0,140.0,1.0,8.0,5.0,1.0,257.0,2.0,1.0,4.0,...,2.0,1.0,1.0,58.0,2.0,2.0,528.0,1.0,1.0,1.0
1440,2.0,124.0,1.0,8.0,5.0,2.0,0.0,1.0,1.0,2.0,...,2.0,1.0,1.0,19.0,2.0,2.0,518.0,1.0,1.0,1.0
1441,2.0,70.0,1.0,1.0,1.0,2.0,0.0,1.0,1.0,4.0,...,1.0,1.0,1.0,5.0,2.0,2.0,470.0,1.0,1.0,1.0
1442,2.0,95.0,1.0,1.0,1.0,3.0,198.0,3.0,2.0,4.0,...,1.0,1.0,1.0,12.0,3.0,3.0,714.0,1.0,1.0,2.0
1443,2.0,88.0,1.0,1.0,1.0,1.0,382.0,1.0,1.0,2.0,...,3.0,1.0,1.0,12.0,3.0,3.0,682.0,1.0,1.0,2.0
1444,2.0,125.0,1.0,15.0,1.0,2.0,0.0,5.0,5.0,5.0,...,2.0,5.0,1.0,55.0,2.0,1.0,270.0,2.0,1.0,1.0
1445,3.0,78.0,1.0,2.0,2.0,1.0,200.0,1.0,1.0,2.0,...,2.0,1.0,1.0,34.0,3.0,4.0,784.0,1.0,1.0,1.0
1446,3.0,41.0,1.0,7.0,7.0,2.0,0.0,1.0,1.0,3.0,...,2.0,1.0,3.0,33.0,1.0,1.0,336.0,1.0,1.0,1.0
1447,2.0,58.0,1.0,8.0,5.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,1.0,22.0,1.0,1.0,288.0,1.0,1.0,1.0
1448,2.0,94.0,1.0,8.0,5.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,6.0,17.0,2.0,3.0,928.0,1.0,1.0,1.0
1449,3.0,21.0,1.0,7.0,7.0,2.0,0.0,1.0,1.0,4.0,...,2.0,1.0,7.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0
1450,3.0,21.0,1.0,7.0,7.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,1.0,68.0,2.0,1.0,253.0,1.0,2.0,1.0
1451,2.0,80.0,1.0,8.0,5.0,1.0,194.0,2.0,1.0,4.0,...,2.0,1.0,1.0,56.0,1.0,1.0,336.0,1.0,1.0,1.0
1452,3.0,21.0,1.0,7.0,7.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,4.0,17.0,2.0,1.0,286.0,1.0,1.0,1.0
1453,3.0,21.0,1.0,7.0,7.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,7.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0
1454,3.0,21.0,1.0,7.0,7.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,7.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0
1455,3.0,21.0,1.0,7.0,7.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,4.0,17.0,2.0,1.0,286.0,1.0,1.0,1.0
1456,2.0,160.0,1.0,1.0,1.0,2.0,0.0,2.0,1.0,1.0,...,2.0,1.0,2.0,15.0,2.0,2.0,576.0,1.0,1.0,1.0
1457,2.0,62.0,1.0,4.0,3.0,2.0,0.0,1.0,1.0,4.0,...,2.0,1.0,7.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0
1458,2.0,74.0,1.0,4.0,4.0,1.0,94.0,1.0,1.0,4.0,...,2.0,1.0,1.0,6.0,3.0,3.0,650.0,1.0,1.0,1.0

## Impute `MSZoning`

In [123]:
column = 'MSZoning'

In [124]:
data_ = no_missingdata
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition']

In [125]:
data_.append(column)

In [126]:
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'MSZoning']

In [127]:
index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
index_na

[455, 756, 790, 1444]

Porcentaje de NaN

In [128]:
(len(index_na)/df_copy.shape[0])*100

0.2741603838245374

In [129]:
df_data_ = df_copy[data_]
df_data_.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,MSZoning
0,20,11622,1,1,1,1,1,12,2,1,...,0,0,0,120,0,0,6,2010,1,1.0
1,20,14267,1,2,1,3,1,12,1,1,...,36,0,0,0,0,12500,6,2010,1,2.0
2,60,13830,1,2,1,1,1,18,1,1,...,34,0,0,0,0,0,3,2010,1,2.0
3,60,9978,1,2,1,1,1,18,1,1,...,36,0,0,0,0,0,6,2010,1,2.0
4,120,5005,1,2,4,1,1,19,1,1,...,82,0,0,144,0,0,1,2010,1,2.0

In [130]:
df_data_[column].unique()

array([ 1.,  2.,  3.,  4.,  5., nan])

In [131]:
impute_ = iterforest.IterImput().complete(df_data_.as_matrix())

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [132]:
impute_

array([[2.0000e+01, 1.1622e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [2.0000e+01, 1.4267e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        2.0000e+00],
       [6.0000e+01, 1.3830e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        2.0000e+00],
       ...,
       [2.0000e+01, 2.0000e+04, 1.0000e+00, ..., 2.0060e+03, 2.0000e+00,
        2.0000e+00],
       [8.5000e+01, 1.0441e+04, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        2.0000e+00],
       [6.0000e+01, 9.6270e+03, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        2.0000e+00]])

In [133]:
df_impute_ = pd.DataFrame(impute_)
df_impute_.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,20.0,11622.0,1.0,1.0,1.0,1.0,1.0,12.0,2.0,1.0,...,0.0,0.0,0.0,120.0,0.0,0.0,6.0,2010.0,1.0,1.0
1,20.0,14267.0,1.0,2.0,1.0,3.0,1.0,12.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,12500.0,6.0,2010.0,1.0,2.0
2,60.0,13830.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,34.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,2.0
3,60.0,9978.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,2.0
4,120.0,5005.0,1.0,2.0,4.0,1.0,1.0,19.0,1.0,1.0,...,82.0,0.0,0.0,144.0,0.0,0.0,1.0,2010.0,1.0,2.0

In [134]:
df_impute_.shape

(1459, 47)

In [135]:
df_impute_.isnull().any().any()

False

In [136]:
df_impute_ = round(df_impute_)

In [137]:
df_impute_.loc[index_na]

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
455,30.0,21780.0,2.0,1.0,1.0,1.0,1.0,14.0,1.0,1.0,...,24.0,0.0,0.0,0.0,0.0,0.0,3.0,2009.0,1.0,4.0
756,20.0,14584.0,1.0,1.0,3.0,1.0,2.0,14.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0,2.0,3.0
790,70.0,56600.0,1.0,2.0,3.0,1.0,1.0,14.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2008.0,1.0,3.0
1444,20.0,31250.0,1.0,1.0,1.0,1.0,1.0,5.0,4.0,1.0,...,0.0,135.0,0.0,0.0,0.0,0.0,5.0,2006.0,1.0,2.0

In [138]:
df_copy[column] = df_impute_[46]

In [139]:
df_copy[column].unique()

array([1., 2., 3., 4., 5.])

## Impute `LotFrontage`

In [140]:
column = 'LotFrontage'

In [141]:
data_ = no_missingdata
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'MSZoning']

In [142]:
data_.remove('MSZoning')

In [143]:
data_.append(column)

In [144]:
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'LotFrontage']

In [145]:
index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
index_na

[6,
 40,
 41,
 45,
 47,
 52,
 59,
 75,
 82,
 98,
 103,
 105,
 107,
 113,
 119,
 124,
 132,
 146,
 152,
 167,
 174,
 177,
 179,
 182,
 183,
 184,
 187,
 188,
 199,
 229,
 230,
 231,
 235,
 238,
 240,
 268,
 271,
 272,
 273,
 274,
 276,
 277,
 279,
 280,
 283,
 286,
 290,
 294,
 297,
 298,
 301,
 308,
 359,
 363,
 373,
 380,
 383,
 386,
 387,
 388,
 401,
 402,
 403,
 412,
 418,
 421,
 423,
 425,
 442,
 450,
 451,
 462,
 476,
 481,
 485,
 487,
 489,
 495,
 497,
 524,
 525,
 528,
 529,
 532,
 536,
 539,
 563,
 569,
 570,
 579,
 581,
 582,
 584,
 589,
 592,
 604,
 614,
 650,
 651,
 662,
 668,
 671,
 677,
 680,
 681,
 682,
 686,
 688,
 695,
 697,
 703,
 704,
 706,
 707,
 710,
 711,
 713,
 714,
 715,
 718,
 726,
 742,
 743,
 744,
 762,
 763,
 774,
 781,
 785,
 790,
 793,
 794,
 797,
 798,
 808,
 819,
 840,
 860,
 865,
 867,
 897,
 901,
 912,
 919,
 927,
 929,
 935,
 936,
 943,
 961,
 963,
 971,
 986,
 999,
 1006,
 1020,
 1023,
 1024,
 1030,
 1031,
 1032,
 1033,
 1038,
 1052,
 1054,
 1061,
 1070,
 1074,
 1075,
 1087,
 1107,
 1108,
 1110,
 1112,
 1123,
 1126,
 1127,
 1134,
 1136,
 1137,
 1142,
 1146,
 1151,
 1154,
 1156,
 1157,
 1160,
 1165,
 1174,
 1176,
 1202,
 1212,
 1213,
 1216,
 1217,
 1220,
 1223,
 1224,
 1240,
 1243,
 1244,
 1246,
 1247,
 1248,
 1249,
 1254,
 1255,
 1264,
 1267,
 1277,
 1278,
 1281,
 1304,
 1347,
 1350,
 1351,
 1352,
 1354,
 1355,
 1358,
 1379,
 1385,
 1387,
 1390,
 1440,
 1441,
 1448]

Porcentaje de NaN

In [146]:
(len(index_na)/df_copy.shape[0])*100

15.558601782042494

In [147]:
df_data_ = df_copy[data_]
df_data_.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,LotFrontage
0,20,11622,1,1,1,1,1,12,2,1,...,0,0,0,120,0,0,6,2010,1,80.0
1,20,14267,1,2,1,3,1,12,1,1,...,36,0,0,0,0,12500,6,2010,1,81.0
2,60,13830,1,2,1,1,1,18,1,1,...,34,0,0,0,0,0,3,2010,1,74.0
3,60,9978,1,2,1,1,1,18,1,1,...,36,0,0,0,0,0,6,2010,1,78.0
4,120,5005,1,2,4,1,1,19,1,1,...,82,0,0,144,0,0,1,2010,1,43.0

In [148]:
df_data_[column].unique()

array([ 80.,  81.,  74.,  78.,  43.,  75.,  nan,  63.,  85.,  70.,  26.,
        21.,  24., 102.,  94.,  90.,  79., 110., 105.,  41., 100.,  67.,
        60.,  73.,  92.,  84.,  39.,  88.,  25.,  30.,  57.,  68.,  98.,
       120.,  87., 119.,  65.,  56.,  69.,  50.,  53.,  52.,  51.,  72.,
        86., 124.,  44.,  83.,  64.,  82.,  38.,  89.,  35.,  58.,  66.,
        93.,  31.,  76.,  28.,  61.,  95., 129.,  59.,  77.,  96.,  47.,
        34., 117.,  48.,  62.,  42., 106., 112.,  32., 115.,  71.,  45.,
       109., 113., 125., 101., 104., 108., 130., 135.,  36.,  55., 136.,
        97.,  91.,  37.,  22., 103.,  99.,  40., 123.,  54., 107., 150.,
       160., 195., 128.,  33., 118., 134., 155., 126.,  46., 149., 200.,
       121., 131., 114.,  49., 133., 140.])

In [149]:
impute_ = iterforest.IterImput().complete(df_data_.as_matrix())

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [150]:
impute_

array([[2.0000e+01, 1.1622e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        8.0000e+01],
       [2.0000e+01, 1.4267e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        8.1000e+01],
       [6.0000e+01, 1.3830e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        7.4000e+01],
       ...,
       [2.0000e+01, 2.0000e+04, 1.0000e+00, ..., 2.0060e+03, 2.0000e+00,
        1.6000e+02],
       [8.5000e+01, 1.0441e+04, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        6.2000e+01],
       [6.0000e+01, 9.6270e+03, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        7.4000e+01]])

In [151]:
df_impute_ = pd.DataFrame(impute_)
df_impute_.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,20.0,11622.0,1.0,1.0,1.0,1.0,1.0,12.0,2.0,1.0,...,0.0,0.0,0.0,120.0,0.0,0.0,6.0,2010.0,1.0,80.0
1,20.0,14267.0,1.0,2.0,1.0,3.0,1.0,12.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,12500.0,6.0,2010.0,1.0,81.0
2,60.0,13830.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,34.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,74.0
3,60.0,9978.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,78.0
4,120.0,5005.0,1.0,2.0,4.0,1.0,1.0,19.0,1.0,1.0,...,82.0,0.0,0.0,144.0,0.0,0.0,1.0,2010.0,1.0,43.0

In [152]:
df_impute_.shape

(1459, 47)

In [153]:
df_impute_.isnull().any().any()

False

In [154]:
df_impute_ = round(df_impute_)

In [155]:
df_impute_.loc[index_na]

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
6,20.0,7980.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,21.0,0.0,0.0,0.0,0.0,500.0,3.0,2010.0,1.0,65.0
40,160.0,2980.0,1.0,1.0,1.0,3.0,1.0,6.0,1.0,1.0,...,32.0,0.0,0.0,0.0,0.0,0.0,5.0,2010.0,1.0,39.0
41,160.0,2403.0,1.0,2.0,1.0,2.0,1.0,6.0,1.0,1.0,...,50.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,24.0
45,20.0,10456.0,1.0,2.0,1.0,1.0,1.0,7.0,1.0,1.0,...,76.0,0.0,0.0,0.0,0.0,0.0,5.0,2010.0,1.0,81.0
47,50.0,18837.0,1.0,2.0,1.0,1.0,1.0,7.0,1.0,1.0,...,69.0,0.0,0.0,0.0,0.0,0.0,4.0,2010.0,1.0,87.0
52,80.0,10600.0,1.0,2.0,1.0,1.0,1.0,12.0,1.0,1.0,...,172.0,0.0,0.0,0.0,0.0,0.0,5.0,2010.0,6.0,78.0
59,20.0,8050.0,1.0,2.0,1.0,1.0,1.0,12.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2010.0,1.0,75.0
75,50.0,8239.0,1.0,1.0,1.0,1.0,1.0,8.0,4.0,1.0,...,0.0,334.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,60.0
82,75.0,7793.0,1.0,2.0,2.0,3.0,1.0,9.0,1.0,1.0,...,0.0,60.0,0.0,0.0,0.0,0.0,5.0,2010.0,1.0,82.0
98,70.0,6449.0,1.0,2.0,1.0,1.0,1.0,24.0,1.0,1.0,...,0.0,239.0,0.0,0.0,0.0,0.0,3.0,2010.0,2.0,59.0
103,90.0,7424.0,1.0,2.0,1.0,1.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2010.0,1.0,66.0
105,20.0,20062.0,1.0,2.0,3.0,1.0,2.0,20.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2010.0,1.0,105.0
107,60.0,17082.0,1.0,2.0,3.0,4.0,2.0,20.0,1.0,1.0,...,104.0,0.0,0.0,0.0,0.0,0.0,5.0,2010.0,1.0,76.0
113,20.0,11200.0,1.0,2.0,1.0,4.0,1.0,16.0,1.0,1.0,...,144.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,57.0
119,60.0,9337.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,...,39.0,0.0,0.0,0.0,0.0,0.0,4.0,2010.0,1.0,70.0
124,120.0,4435.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2010.0,1.0,35.0
132,30.0,7890.0,1.0,1.0,1.0,3.0,1.0,24.0,1.0,1.0,...,0.0,0.0,0.0,166.0,0.0,0.0,3.0,2010.0,1.0,71.0
146,90.0,12760.0,1.0,2.0,1.0,1.0,1.0,5.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,101.0
152,20.0,11875.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,83.0
167,60.0,11792.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,46.0,0.0,0.0,0.0,0.0,0.0,8.0,2009.0,1.0,83.0
174,60.0,8803.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,46.0,0.0,0.0,0.0,0.0,0.0,7.0,2009.0,1.0,63.0
177,60.0,13250.0,1.0,2.0,1.0,1.0,1.0,7.0,6.0,1.0,...,192.0,0.0,0.0,0.0,0.0,0.0,5.0,2009.0,2.0,88.0
179,60.0,12388.0,1.0,2.0,1.0,1.0,1.0,7.0,1.0,1.0,...,84.0,0.0,0.0,0.0,0.0,0.0,8.0,2009.0,1.0,97.0
182,60.0,7500.0,1.0,1.0,1.0,1.0,1.0,6.0,6.0,1.0,...,134.0,0.0,0.0,0.0,0.0,0.0,3.0,2009.0,1.0,71.0
183,60.0,8470.0,1.0,1.0,1.0,3.0,1.0,6.0,1.0,1.0,...,48.0,0.0,0.0,0.0,0.0,0.0,10.0,2009.0,1.0,70.0
184,20.0,9373.0,1.0,2.0,1.0,4.0,1.0,7.0,3.0,1.0,...,0.0,0.0,0.0,490.0,0.0,0.0,6.0,2009.0,1.0,55.0
187,20.0,7830.0,1.0,2.0,1.0,1.0,1.0,12.0,1.0,1.0,...,45.0,0.0,0.0,0.0,0.0,0.0,3.0,2009.0,1.0,75.0
188,20.0,8510.0,1.0,2.0,1.0,1.0,1.0,12.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,2009.0,1.0,78.0
199,20.0,10710.0,1.0,1.0,1.0,1.0,1.0,12.0,1.0,1.0,...,162.0,0.0,0.0,0.0,0.0,1200.0,7.0,2009.0,1.0,78.0
229,60.0,8965.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,75.0,0.0,0.0,0.0,0.0,0.0,6.0,2009.0,1.0,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,60.0,12585.0,1.0,2.0,1.0,1.0,1.0,4.0,1.0,1.0,...,136.0,0.0,0.0,0.0,0.0,0.0,10.0,2006.0,1.0,94.0
1240,60.0,9019.0,1.0,2.0,1.0,1.0,1.0,13.0,5.0,1.0,...,40.0,0.0,0.0,0.0,0.0,0.0,7.0,2006.0,1.0,67.0
1243,20.0,9240.0,1.0,2.0,1.0,1.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2006.0,1.0,75.0
1244,20.0,9308.0,1.0,2.0,1.0,4.0,1.0,10.0,9.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,2006.0,1.0,51.0
1246,20.0,8638.0,1.0,2.0,1.0,1.0,1.0,10.0,5.0,1.0,...,74.0,0.0,0.0,0.0,0.0,0.0,10.0,2006.0,1.0,67.0
1247,20.0,13052.0,1.0,2.0,1.0,4.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2006.0,1.0,58.0
1248,20.0,8020.0,1.0,2.0,1.0,1.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2006.0,1.0,76.0
1249,20.0,8789.0,1.0,2.0,1.0,1.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,2006.0,1.0,74.0
1254,160.0,2998.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0,1.0,...,32.0,0.0,0.0,0.0,0.0,0.0,6.0,2006.0,1.0,39.0
1255,160.0,4447.0,1.0,2.0,1.0,2.0,1.0,6.0,1.0,1.0,...,50.0,0.0,0.0,0.0,0.0,0.0,7.0,2006.0,1.0,36.0
1264,20.0,9759.0,1.0,2.0,1.0,1.0,1.0,12.0,1.0,1.0,...,88.0,0.0,0.0,0.0,0.0,0.0,3.0,2006.0,1.0,76.0
1267,20.0,10368.0,1.0,2.0,1.0,4.0,1.0,12.0,1.0,1.0,...,60.0,0.0,0.0,0.0,0.0,0.0,4.0,2006.0,1.0,54.0
1277,90.0,8917.0,1.0,2.0,1.0,1.0,1.0,12.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,10.0,2006.0,1.0,73.0
1278,80.0,12700.0,1.0,2.0,1.0,1.0,1.0,12.0,1.0,1.0,...,69.0,0.0,0.0,0.0,0.0,0.0,11.0,2006.0,1.0,92.0
1281,20.0,9610.0,1.0,2.0,1.0,3.0,1.0,12.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,12.0,2006.0,1.0,84.0
1304,60.0,18275.0,1.0,2.0,4.0,1.0,1.0,12.0,1.0,1.0,...,102.0,0.0,0.0,0.0,0.0,0.0,9.0,2006.0,1.0,116.0
1347,20.0,11327.0,1.0,2.0,1.0,1.0,1.0,10.0,1.0,1.0,...,48.0,0.0,0.0,0.0,0.0,0.0,6.0,2006.0,1.0,74.0
1350,20.0,9535.0,1.0,2.0,1.0,1.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,2006.0,1.0,77.0
1351,80.0,7176.0,1.0,2.0,1.0,4.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,180.0,0.0,0.0,7.0,2006.0,1.0,65.0
1352,90.0,9662.0,1.0,2.0,1.0,1.0,1.0,10.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,8.0,2006.0,1.0,81.0
1354,30.0,17529.0,1.0,1.0,1.0,1.0,1.0,10.0,1.0,1.0,...,0.0,116.0,0.0,0.0,0.0,0.0,4.0,2006.0,1.0,88.0
1355,20.0,20355.0,1.0,1.0,3.0,1.0,2.0,20.0,1.0,1.0,...,115.0,168.0,0.0,0.0,0.0,0.0,6.0,2006.0,1.0,122.0
1358,150.0,1700.0,1.0,1.0,4.0,1.0,1.0,20.0,1.0,1.0,...,36.0,0.0,0.0,200.0,0.0,0.0,4.0,2006.0,1.0,26.0
1379,20.0,8685.0,1.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0,...,130.0,0.0,0.0,0.0,0.0,0.0,5.0,2006.0,1.0,57.0
1385,60.0,9930.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,...,54.0,0.0,0.0,0.0,0.0,0.0,7.0,2006.0,1.0,71.0
1387,20.0,11088.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,...,166.0,0.0,0.0,0.0,0.0,0.0,6.0,2006.0,1.0,79.0
1390,60.0,21533.0,1.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0,...,48.0,0.0,0.0,0.0,0.0,0.0,8.0,2006.0,1.0,87.0
1440,20.0,50102.0,1.0,2.0,3.0,1.0,2.0,17.0,1.0,1.0,...,0.0,0.0,0.0,138.0,0.0,0.0,3.0,2006.0,5.0,124.0
1441,20.0,8098.0,1.0,2.0,1.0,1.0,1.0,17.0,1.0,1.0,...,173.0,0.0,0.0,0.0,0.0,0.0,10.0,2006.0,1.0,70.0
1448,90.0,11836.0,1.0,2.0,1.0,3.0,1.0,5.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2006.0,1.0,94.0

In [156]:
df_copy[column] = df_impute_[46]

In [157]:
df_copy[column].unique()

array([ 80.,  81.,  74.,  78.,  43.,  75.,  65.,  63.,  85.,  70.,  26.,
        21.,  24., 102.,  94.,  90.,  79., 110., 105.,  41., 100.,  67.,
        60.,  73.,  92.,  84.,  39.,  88.,  25.,  30.,  57.,  68.,  87.,
        98., 120., 119.,  56.,  69.,  50.,  53.,  82.,  52.,  51.,  72.,
        59.,  66.,  86.,  76., 124.,  44.,  83.,  64.,  38.,  35.,  89.,
        71.,  58., 101.,  93.,  31.,  28.,  61.,  97.,  55.,  95., 129.,
        77.,  96.,  47.,  34., 117.,  48.,  62.,  42., 106.,  54., 112.,
        32.,  40.,  99., 115.,  45., 118., 109., 113., 125., 111., 104.,
       108., 130., 135.,  36., 136.,  91.,  37.,  22., 103., 123., 107.,
       150., 160., 195., 128.,  33., 134., 155., 126.,  46., 149., 200.,
       121., 131., 114.,  49., 116., 122., 133., 140.])

## Impute `Utilities`

In [158]:
column = 'Utilities'

In [159]:
data_ = no_missingdata
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'LotFrontage']

In [160]:
data_.remove('LotFrontage')

In [161]:
data_.append(column)

In [162]:
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'Utilities']

In [163]:
index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
index_na

[455, 485]

Porcentaje de NaN

In [164]:
(len(index_na)/df_copy.shape[0])*100

0.1370801919122687

In [165]:
df_data_ = df_copy[data_]
df_data_.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,Utilities
0,20,11622,1,1,1,1,1,12,2,1,...,0,0,0,120,0,0,6,2010,1,1.0
1,20,14267,1,2,1,3,1,12,1,1,...,36,0,0,0,0,12500,6,2010,1,1.0
2,60,13830,1,2,1,1,1,18,1,1,...,34,0,0,0,0,0,3,2010,1,1.0
3,60,9978,1,2,1,1,1,18,1,1,...,36,0,0,0,0,0,6,2010,1,1.0
4,120,5005,1,2,4,1,1,19,1,1,...,82,0,0,144,0,0,1,2010,1,1.0

In [166]:
df_data_[column].unique()

array([ 1., nan])

In [167]:
impute_ = iterforest.IterImput().complete(df_data_.as_matrix())

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [168]:
impute_

array([[2.0000e+01, 1.1622e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [2.0000e+01, 1.4267e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [6.0000e+01, 1.3830e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       ...,
       [2.0000e+01, 2.0000e+04, 1.0000e+00, ..., 2.0060e+03, 2.0000e+00,
        1.0000e+00],
       [8.5000e+01, 1.0441e+04, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        1.0000e+00],
       [6.0000e+01, 9.6270e+03, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        1.0000e+00]])

In [169]:
df_impute_ = pd.DataFrame(impute_)
df_impute_.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,20.0,11622.0,1.0,1.0,1.0,1.0,1.0,12.0,2.0,1.0,...,0.0,0.0,0.0,120.0,0.0,0.0,6.0,2010.0,1.0,1.0
1,20.0,14267.0,1.0,2.0,1.0,3.0,1.0,12.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,12500.0,6.0,2010.0,1.0,1.0
2,60.0,13830.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,34.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,1.0
3,60.0,9978.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,1.0
4,120.0,5005.0,1.0,2.0,4.0,1.0,1.0,19.0,1.0,1.0,...,82.0,0.0,0.0,144.0,0.0,0.0,1.0,2010.0,1.0,1.0

In [170]:
df_impute_.shape

(1459, 47)

In [171]:
df_impute_.isnull().any().any()

False

In [172]:
df_impute_ = round(df_impute_)

In [173]:
df_impute_.loc[index_na]

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
455,30.0,21780.0,2.0,1.0,1.0,1.0,1.0,14.0,1.0,1.0,...,24.0,0.0,0.0,0.0,0.0,0.0,3.0,2009.0,1.0,1.0
485,20.0,31220.0,1.0,2.0,2.0,2.0,1.0,18.0,2.0,1.0,...,0.0,144.0,0.0,0.0,0.0,750.0,5.0,2008.0,1.0,1.0

In [174]:
df_copy[column] = df_impute_[46]

In [175]:
df_copy[column].unique()

array([1.])

## Impute `KitchenQual`

In [176]:
column = 'KitchenQual'

In [177]:
data_ = no_missingdata
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'Utilities']

In [178]:
data_.remove('Utilities')

In [179]:
data_.append(column)

In [180]:
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'KitchenQual']

In [181]:
index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
index_na

[95]

Porcentaje de NaN

In [182]:
(len(index_na)/df_copy.shape[0])*100

0.06854009595613435

In [183]:
df_data_ = df_copy[data_]
df_data_.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,KitchenQual
0,20,11622,1,1,1,1,1,12,2,1,...,0,0,0,120,0,0,6,2010,1,2.0
1,20,14267,1,2,1,3,1,12,1,1,...,36,0,0,0,0,12500,6,2010,1,1.0
2,60,13830,1,2,1,1,1,18,1,1,...,34,0,0,0,0,0,3,2010,1,2.0
3,60,9978,1,2,1,1,1,18,1,1,...,36,0,0,0,0,0,6,2010,1,1.0
4,120,5005,1,2,4,1,1,19,1,1,...,82,0,0,144,0,0,1,2010,1,1.0

In [184]:
df_data_[column].unique()

array([ 2.,  1.,  3.,  4., nan])

In [185]:
impute_ = iterforest.IterImput().complete(df_data_.as_matrix())

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [186]:
impute_

array([[2.0000e+01, 1.1622e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        2.0000e+00],
       [2.0000e+01, 1.4267e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [6.0000e+01, 1.3830e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        2.0000e+00],
       ...,
       [2.0000e+01, 2.0000e+04, 1.0000e+00, ..., 2.0060e+03, 2.0000e+00,
        2.0000e+00],
       [8.5000e+01, 1.0441e+04, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        2.0000e+00],
       [6.0000e+01, 9.6270e+03, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        2.0000e+00]])

In [187]:
df_impute_ = pd.DataFrame(impute_)
df_impute_.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,20.0,11622.0,1.0,1.0,1.0,1.0,1.0,12.0,2.0,1.0,...,0.0,0.0,0.0,120.0,0.0,0.0,6.0,2010.0,1.0,2.0
1,20.0,14267.0,1.0,2.0,1.0,3.0,1.0,12.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,12500.0,6.0,2010.0,1.0,1.0
2,60.0,13830.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,34.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,2.0
3,60.0,9978.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,1.0
4,120.0,5005.0,1.0,2.0,4.0,1.0,1.0,19.0,1.0,1.0,...,82.0,0.0,0.0,144.0,0.0,0.0,1.0,2010.0,1.0,1.0

In [188]:
df_impute_.shape

(1459, 47)

In [189]:
df_impute_.isnull().any().any()

False

In [190]:
df_impute_ = round(df_impute_)

In [191]:
df_impute_.loc[index_na]

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
95,50.0,10632.0,1.0,2.0,1.0,1.0,1.0,20.0,1.0,1.0,...,0.0,248.0,0.0,0.0,0.0,0.0,1.0,2010.0,1.0,2.0

In [192]:
df_copy[column] = df_impute_[46]

In [193]:
df_copy[column].unique()

array([2., 1., 3., 4.])

## Impute `Functional`

In [194]:
column = 'Functional'

In [195]:
data_ = no_missingdata
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'KitchenQual']

In [196]:
data_.remove('KitchenQual')

In [197]:
data_.append(column)

In [198]:
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'Functional']

In [199]:
index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
index_na

[756, 1013]

Porcentaje de NaN

In [200]:
(len(index_na)/df_copy.shape[0])*100

0.1370801919122687

In [201]:
df_data_ = df_copy[data_]
df_data_.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,Functional
0,20,11622,1,1,1,1,1,12,2,1,...,0,0,0,120,0,0,6,2010,1,1.0
1,20,14267,1,2,1,3,1,12,1,1,...,36,0,0,0,0,12500,6,2010,1,1.0
2,60,13830,1,2,1,1,1,18,1,1,...,34,0,0,0,0,0,3,2010,1,1.0
3,60,9978,1,2,1,1,1,18,1,1,...,36,0,0,0,0,0,6,2010,1,1.0
4,120,5005,1,2,4,1,1,19,1,1,...,82,0,0,144,0,0,1,2010,1,1.0

In [202]:
df_data_[column].unique()

array([ 1.,  4.,  2.,  5.,  3.,  7.,  6., nan])

In [203]:
impute_ = iterforest.IterImput().complete(df_data_.as_matrix())

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [204]:
impute_

array([[2.0000e+01, 1.1622e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [2.0000e+01, 1.4267e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [6.0000e+01, 1.3830e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       ...,
       [2.0000e+01, 2.0000e+04, 1.0000e+00, ..., 2.0060e+03, 2.0000e+00,
        1.0000e+00],
       [8.5000e+01, 1.0441e+04, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        1.0000e+00],
       [6.0000e+01, 9.6270e+03, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        1.0000e+00]])

In [205]:
df_impute_ = pd.DataFrame(impute_)
df_impute_.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,20.0,11622.0,1.0,1.0,1.0,1.0,1.0,12.0,2.0,1.0,...,0.0,0.0,0.0,120.0,0.0,0.0,6.0,2010.0,1.0,1.0
1,20.0,14267.0,1.0,2.0,1.0,3.0,1.0,12.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,12500.0,6.0,2010.0,1.0,1.0
2,60.0,13830.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,34.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,1.0
3,60.0,9978.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,1.0
4,120.0,5005.0,1.0,2.0,4.0,1.0,1.0,19.0,1.0,1.0,...,82.0,0.0,0.0,144.0,0.0,0.0,1.0,2010.0,1.0,1.0

In [206]:
df_impute_.shape

(1459, 47)

In [207]:
df_impute_.isnull().any().any()

False

In [208]:
df_impute_ = round(df_impute_)

In [209]:
df_impute_.loc[index_na]

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
756,20.0,14584.0,1.0,1.0,3.0,1.0,2.0,14.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0,2.0,4.0
1013,50.0,10320.0,1.0,1.0,1.0,3.0,1.0,14.0,4.0,1.0,...,211.0,0.0,0.0,84.0,0.0,0.0,9.0,2007.0,2.0,3.0

In [210]:
df_copy[column] = df_impute_[46]

In [211]:
df_copy[column].unique()

array([1., 4., 2., 5., 3., 7., 6.])

## Impute `SaleType`

In [212]:
column = 'SaleType'

In [213]:
data_ = no_missingdata
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'Functional']

In [214]:
data_.remove('Functional')

In [215]:
data_.append(column)

In [216]:
data_

['MSSubClass',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleCondition',
 'SaleType']

In [217]:
index_na = pd.isnull(df_copy[data_]).any(1).nonzero()[0].tolist()
index_na

[1029]

Porcentaje de NaN

In [218]:
(len(index_na)/df_copy.shape[0])*100

0.06854009595613435

In [219]:
df_data_ = df_copy[data_]
df_data_.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,SaleType
0,20,11622,1,1,1,1,1,12,2,1,...,0,0,0,120,0,0,6,2010,1,1.0
1,20,14267,1,2,1,3,1,12,1,1,...,36,0,0,0,0,12500,6,2010,1,1.0
2,60,13830,1,2,1,1,1,18,1,1,...,34,0,0,0,0,0,3,2010,1,1.0
3,60,9978,1,2,1,1,1,18,1,1,...,36,0,0,0,0,0,6,2010,1,1.0
4,120,5005,1,2,4,1,1,19,1,1,...,82,0,0,144,0,0,1,2010,1,1.0

In [220]:
df_data_[column].unique()

array([ 1.,  3.,  2.,  4.,  9.,  8.,  7.,  5.,  6., nan])

In [221]:
impute_ = iterforest.IterImput().complete(df_data_.as_matrix())

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [222]:
impute_

array([[2.0000e+01, 1.1622e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [2.0000e+01, 1.4267e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       [6.0000e+01, 1.3830e+04, 1.0000e+00, ..., 2.0100e+03, 1.0000e+00,
        1.0000e+00],
       ...,
       [2.0000e+01, 2.0000e+04, 1.0000e+00, ..., 2.0060e+03, 2.0000e+00,
        1.0000e+00],
       [8.5000e+01, 1.0441e+04, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        1.0000e+00],
       [6.0000e+01, 9.6270e+03, 1.0000e+00, ..., 2.0060e+03, 1.0000e+00,
        1.0000e+00]])

In [223]:
df_impute_ = pd.DataFrame(impute_)
df_impute_.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,20.0,11622.0,1.0,1.0,1.0,1.0,1.0,12.0,2.0,1.0,...,0.0,0.0,0.0,120.0,0.0,0.0,6.0,2010.0,1.0,1.0
1,20.0,14267.0,1.0,2.0,1.0,3.0,1.0,12.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,12500.0,6.0,2010.0,1.0,1.0
2,60.0,13830.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,34.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,1.0,1.0
3,60.0,9978.0,1.0,2.0,1.0,1.0,1.0,18.0,1.0,1.0,...,36.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0,1.0,1.0
4,120.0,5005.0,1.0,2.0,4.0,1.0,1.0,19.0,1.0,1.0,...,82.0,0.0,0.0,144.0,0.0,0.0,1.0,2010.0,1.0,1.0

In [224]:
df_impute_.shape

(1459, 47)

In [225]:
df_impute_.isnull().any().any()

False

In [226]:
df_impute_ = round(df_impute_)

In [227]:
df_impute_.loc[index_na]

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
1029,20.0,13770.0,1.0,1.0,1.0,3.0,1.0,10.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,10.0,2007.0,1.0,1.0

In [228]:
df_copy[column] = df_impute_[46]

In [229]:
df_copy[column].unique()

array([1., 3., 2., 4., 9., 8., 7., 5., 6.])

## MasVnrType -> MasVnrArea

## Categorize `MasVnrType`

* 5 ->`NA`: No Masonry

In [230]:
column = 'MasVnrType'

In [231]:
df_copy[column].unique()

array([ 2.,  1.,  3.,  4., nan])

In [232]:
df_copy[column].fillna(value=5, inplace=True)

In [233]:
df_copy[column].unique()

array([2., 1., 3., 4., 5.])

## Categorize `MasVnrArea`

* 0 ->`NA`: No Masonry

In [236]:
column = 'MasVnrArea'

In [237]:
df_copy[column].unique()

array([0.000e+00, 1.080e+02, 2.000e+01, 5.040e+02, 4.920e+02, 1.620e+02,
       2.560e+02, 6.150e+02, 2.400e+02, 1.095e+03, 2.320e+02, 1.780e+02,
       1.400e+01, 1.140e+02, 2.260e+02, 1.220e+02, 2.500e+02, 1.800e+02,
       1.200e+02, 2.160e+02, 1.159e+03, 1.720e+02, 2.680e+02, 1.440e+02,
       2.650e+02, 3.400e+02, 5.060e+02, 1.500e+02, 9.100e+01, 4.320e+02,
       2.180e+02, 7.710e+02, 3.000e+02, 9.000e+01, 7.200e+01, 4.700e+01,
       2.880e+02, 9.600e+01, 1.770e+02, 8.500e+01, 8.000e+01, 3.200e+02,
       1.700e+02, 2.030e+02, 3.710e+02, 4.300e+02, 4.400e+01, 1.860e+02,
       6.000e+01, 4.400e+02, 1.880e+02, 3.200e+01, 4.500e+01, 1.570e+02,
       1.010e+02, 2.290e+02, 1.610e+02, 1.960e+02, 4.250e+02, 1.650e+02,
       7.260e+02, 4.500e+02, 4.720e+02, 3.020e+02, 2.380e+02, 2.840e+02,
       2.850e+02, 4.180e+02, 7.240e+02, 3.830e+02, 1.350e+02, 1.760e+02,
       7.300e+02, 4.700e+02, 3.080e+02, 5.000e+02, 2.700e+02, 1.630e+02,
       1.600e+01, 2.000e+02,       nan, 2.100e+02, 6.340e+02, 2.860e+02,
       3.720e+02, 2.940e+02, 2.600e+02, 2.060e+02, 1.980e+02, 1.210e+02,
       2.640e+02, 1.400e+02, 1.320e+02, 1.410e+02, 1.150e+02, 2.800e+02,
       2.520e+02, 5.130e+02, 1.280e+02, 2.830e+02, 5.090e+02, 1.600e+02,
       7.000e+01, 2.170e+02, 3.000e+00, 1.640e+02, 6.570e+02, 4.800e+02,
       2.950e+02, 1.430e+02, 8.200e+01, 4.200e+02, 1.240e+02, 4.440e+02,
       2.300e+01, 5.400e+01, 3.660e+02, 1.490e+02, 1.000e+02, 2.420e+02,
       3.640e+02, 3.520e+02, 7.600e+01, 6.800e+01, 4.000e+01, 2.090e+02,
       7.400e+01, 2.590e+02, 8.800e+01, 1.740e+02, 2.460e+02, 4.060e+02,
       3.100e+02, 2.900e+02, 1.820e+02, 1.190e+02, 1.940e+02, 1.300e+02,
       2.960e+02, 1.020e+02, 6.210e+02, 1.680e+02, 4.020e+02, 3.590e+02,
       4.220e+02, 3.560e+02, 5.540e+02, 4.680e+02, 3.680e+02, 1.260e+02,
       6.800e+02, 1.110e+03, 2.210e+02, 7.140e+02, 1.060e+02, 2.400e+01,
       6.470e+02, 1.290e+03, 4.950e+02, 4.660e+02, 1.560e+02, 2.920e+02,
       9.500e+01, 3.800e+01, 1.450e+02, 3.040e+02, 5.680e+02, 1.790e+02,
       4.560e+02, 1.050e+03, 4.100e+02, 1.870e+02, 5.200e+01, 8.400e+01,
       3.600e+02, 1.250e+02, 2.760e+02, 3.900e+01, 2.750e+02, 1.900e+02,
       2.510e+02, 2.270e+02, 1.340e+02, 1.920e+02, 2.050e+02, 5.000e+01,
       2.120e+02, 2.220e+02, 5.800e+01, 6.680e+02, 2.580e+02, 2.280e+02,
       6.740e+02, 1.970e+02, 9.800e+01, 1.380e+02, 1.460e+02, 7.100e+02,
       9.450e+02, 3.060e+02, 6.700e+01, 5.490e+02, 2.530e+02, 5.670e+02,
       3.780e+02, 4.000e+02, 3.650e+02, 9.700e+02, 5.100e+02, 5.020e+02,
       3.940e+02, 2.350e+02, 2.200e+01, 5.150e+02, 3.090e+02, 5.260e+02,
       2.480e+02, 7.540e+02, 1.480e+02, 2.980e+02, 3.530e+02, 2.720e+02,
       3.000e+01, 3.600e+01, 3.420e+02, 6.000e+02, 4.100e+01, 5.250e+02,
       1.120e+02, 5.600e+01, 2.020e+02, 1.360e+02, 8.700e+01, 2.910e+02,
       6.900e+01, 2.890e+02, 5.300e+01, 8.600e+01, 2.790e+02, 1.000e+00,
       2.340e+02, 4.420e+02, 8.900e+01, 3.230e+02, 2.040e+02, 1.130e+02,
       5.100e+01, 2.140e+02, 5.190e+02, 2.540e+02, 1.580e+02, 1.224e+03,
       4.230e+02, 6.520e+02, 4.730e+02, 1.660e+02, 8.860e+02, 9.400e+01,
       1.890e+02, 2.800e+01, 2.440e+02, 9.020e+02, 4.340e+02, 6.620e+02,
       1.840e+02, 7.340e+02, 5.500e+02, 2.300e+02, 5.140e+02, 3.800e+02,
       2.150e+02, 3.850e+02, 1.420e+02, 2.780e+02, 5.180e+02, 5.720e+02,
       2.360e+02, 1.800e+01, 3.220e+02, 8.770e+02, 3.970e+02, 7.380e+02,
       5.010e+02, 1.180e+02, 6.920e+02, 3.320e+02, 6.320e+02, 5.220e+02,
       3.790e+02, 1.040e+02, 3.050e+02, 9.900e+01, 6.500e+01, 1.230e+02,
       1.530e+02, 5.320e+02, 6.200e+01, 1.990e+02, 2.610e+02, 3.550e+02,
       4.050e+02, 3.270e+02, 2.570e+02, 3.820e+02])

In [238]:
df_copy[column].fillna(value=0, inplace=True)

In [239]:
df_copy[column].unique()

array([0.000e+00, 1.080e+02, 2.000e+01, 5.040e+02, 4.920e+02, 1.620e+02,
       2.560e+02, 6.150e+02, 2.400e+02, 1.095e+03, 2.320e+02, 1.780e+02,
       1.400e+01, 1.140e+02, 2.260e+02, 1.220e+02, 2.500e+02, 1.800e+02,
       1.200e+02, 2.160e+02, 1.159e+03, 1.720e+02, 2.680e+02, 1.440e+02,
       2.650e+02, 3.400e+02, 5.060e+02, 1.500e+02, 9.100e+01, 4.320e+02,
       2.180e+02, 7.710e+02, 3.000e+02, 9.000e+01, 7.200e+01, 4.700e+01,
       2.880e+02, 9.600e+01, 1.770e+02, 8.500e+01, 8.000e+01, 3.200e+02,
       1.700e+02, 2.030e+02, 3.710e+02, 4.300e+02, 4.400e+01, 1.860e+02,
       6.000e+01, 4.400e+02, 1.880e+02, 3.200e+01, 4.500e+01, 1.570e+02,
       1.010e+02, 2.290e+02, 1.610e+02, 1.960e+02, 4.250e+02, 1.650e+02,
       7.260e+02, 4.500e+02, 4.720e+02, 3.020e+02, 2.380e+02, 2.840e+02,
       2.850e+02, 4.180e+02, 7.240e+02, 3.830e+02, 1.350e+02, 1.760e+02,
       7.300e+02, 4.700e+02, 3.080e+02, 5.000e+02, 2.700e+02, 1.630e+02,
       1.600e+01, 2.000e+02, 2.100e+02, 6.340e+02, 2.860e+02, 3.720e+02,
       2.940e+02, 2.600e+02, 2.060e+02, 1.980e+02, 1.210e+02, 2.640e+02,
       1.400e+02, 1.320e+02, 1.410e+02, 1.150e+02, 2.800e+02, 2.520e+02,
       5.130e+02, 1.280e+02, 2.830e+02, 5.090e+02, 1.600e+02, 7.000e+01,
       2.170e+02, 3.000e+00, 1.640e+02, 6.570e+02, 4.800e+02, 2.950e+02,
       1.430e+02, 8.200e+01, 4.200e+02, 1.240e+02, 4.440e+02, 2.300e+01,
       5.400e+01, 3.660e+02, 1.490e+02, 1.000e+02, 2.420e+02, 3.640e+02,
       3.520e+02, 7.600e+01, 6.800e+01, 4.000e+01, 2.090e+02, 7.400e+01,
       2.590e+02, 8.800e+01, 1.740e+02, 2.460e+02, 4.060e+02, 3.100e+02,
       2.900e+02, 1.820e+02, 1.190e+02, 1.940e+02, 1.300e+02, 2.960e+02,
       1.020e+02, 6.210e+02, 1.680e+02, 4.020e+02, 3.590e+02, 4.220e+02,
       3.560e+02, 5.540e+02, 4.680e+02, 3.680e+02, 1.260e+02, 6.800e+02,
       1.110e+03, 2.210e+02, 7.140e+02, 1.060e+02, 2.400e+01, 6.470e+02,
       1.290e+03, 4.950e+02, 4.660e+02, 1.560e+02, 2.920e+02, 9.500e+01,
       3.800e+01, 1.450e+02, 3.040e+02, 5.680e+02, 1.790e+02, 4.560e+02,
       1.050e+03, 4.100e+02, 1.870e+02, 5.200e+01, 8.400e+01, 3.600e+02,
       1.250e+02, 2.760e+02, 3.900e+01, 2.750e+02, 1.900e+02, 2.510e+02,
       2.270e+02, 1.340e+02, 1.920e+02, 2.050e+02, 5.000e+01, 2.120e+02,
       2.220e+02, 5.800e+01, 6.680e+02, 2.580e+02, 2.280e+02, 6.740e+02,
       1.970e+02, 9.800e+01, 1.380e+02, 1.460e+02, 7.100e+02, 9.450e+02,
       3.060e+02, 6.700e+01, 5.490e+02, 2.530e+02, 5.670e+02, 3.780e+02,
       4.000e+02, 3.650e+02, 9.700e+02, 5.100e+02, 5.020e+02, 3.940e+02,
       2.350e+02, 2.200e+01, 5.150e+02, 3.090e+02, 5.260e+02, 2.480e+02,
       7.540e+02, 1.480e+02, 2.980e+02, 3.530e+02, 2.720e+02, 3.000e+01,
       3.600e+01, 3.420e+02, 6.000e+02, 4.100e+01, 5.250e+02, 1.120e+02,
       5.600e+01, 2.020e+02, 1.360e+02, 8.700e+01, 2.910e+02, 6.900e+01,
       2.890e+02, 5.300e+01, 8.600e+01, 2.790e+02, 1.000e+00, 2.340e+02,
       4.420e+02, 8.900e+01, 3.230e+02, 2.040e+02, 1.130e+02, 5.100e+01,
       2.140e+02, 5.190e+02, 2.540e+02, 1.580e+02, 1.224e+03, 4.230e+02,
       6.520e+02, 4.730e+02, 1.660e+02, 8.860e+02, 9.400e+01, 1.890e+02,
       2.800e+01, 2.440e+02, 9.020e+02, 4.340e+02, 6.620e+02, 1.840e+02,
       7.340e+02, 5.500e+02, 2.300e+02, 5.140e+02, 3.800e+02, 2.150e+02,
       3.850e+02, 1.420e+02, 2.780e+02, 5.180e+02, 5.720e+02, 2.360e+02,
       1.800e+01, 3.220e+02, 8.770e+02, 3.970e+02, 7.380e+02, 5.010e+02,
       1.180e+02, 6.920e+02, 3.320e+02, 6.320e+02, 5.220e+02, 3.790e+02,
       1.040e+02, 3.050e+02, 9.900e+01, 6.500e+01, 1.230e+02, 1.530e+02,
       5.320e+02, 6.200e+01, 1.990e+02, 2.610e+02, 3.550e+02, 4.050e+02,
       3.270e+02, 2.570e+02, 3.820e+02])

## BsmtQual -> BsmtCond -> BsmtExposure -> BsmtFinType1 -> BsmtFinSF1 -> BsmtFinType2 -> BsmtFinSF2 -> BsmtUnfSF -> TotalBsmtSF -> BsmtFullBath -> BsmtHalfBath

## Categorize `BsmtQual`

* 5 ->`NA`: No Basement

In [240]:
column = 'BsmtQual'

In [241]:
df_copy[column].unique()

array([ 2.,  1.,  3.,  4., nan])

In [242]:
df_copy[column].fillna(value=5, inplace=True)

In [243]:
df_copy[column].unique()

array([2., 1., 3., 4., 5.])

## Categorize `BsmtCond`

* 5 ->`NA`: No Basement

In [244]:
column = 'BsmtCond'

In [245]:
df_copy[column].unique()

array([ 1.,  4.,  3.,  2., nan])

In [246]:
df_copy[column].fillna(value=5, inplace=True)

In [247]:
df_copy[column].unique()

array([1., 4., 3., 2., 5.])

## Categorize `BsmtExposure`

* 5 ->`NA`: No Basement

In [248]:
column = 'BsmtExposure'

In [249]:
df_copy[column].unique()

array([ 1.,  2.,  3.,  4., nan])

In [250]:
df_copy[column].fillna(value=5, inplace=True)

In [251]:
df_copy[column].unique()

array([1., 2., 3., 4., 5.])

## Categorize `BsmtFinType1`

* 7 ->`NA`: No Basement

In [252]:
column = 'BsmtFinType1'

In [253]:
df_copy[column].unique()

array([ 4.,  2.,  1.,  3.,  5.,  6., nan])

In [254]:
df_copy[column].fillna(value=7, inplace=True)

In [255]:
df_copy[column].unique()

array([4., 2., 1., 3., 5., 6., 7.])

## Categorize `BsmtFinSF1`

* 0 ->`NA`: No Basement

In [258]:
column = 'BsmtFinSF1'

In [259]:
df_copy[column].unique()

array([ 468.,  923.,  791.,  602.,  263.,    0.,  935.,  637.,  804.,
       1051.,  156.,  300.,  514.,  110.,   28., 1373.,  578.,   24.,
         16.,  326., 1414.,  126.,  250., 1129., 1298.,  280.,  368.,
        376.,  466.,  244., 1032.,  484.,  833.,  506., 1137.,  687.,
        329.,  698., 1059., 1010., 1500.,  670.,  944., 1188.,  856.,
        936.,  734.,  339.,  648.,  532.,  481.,  588.,  717.,   48.,
        579.,  274.,  780.,  176.,  283.,  788.,  474.,  188.,  452.,
        264.,  360.,  276.,  448.,  960.,  766., 1026.,   73.,  736.,
        704.,  240.,  775., 1319.,  267., 1092.,  964.,  288.,  104.,
        192.,  954., 1346., 1433.,  860.,  870.,  353.,  198.,  480.,
       1682.,  672., 1070.,  528.,  133.,  238.,  426.,  375.,  343.,
        747.,   76.,  308.,  615.,  679.,   78.,   42.,  915.,  294.,
        469.,  207.,  458.,  476., 1341.,  564.,  844.,  847.,  850.,
        284., 1965.,  341.,  741.,  189.,  600.,  400.,  363.,  832.,
        622.,  225., 1333.,  888.,  636.,  500.,  726.,  254.,  306.,
        435.,  389.,  320.,  279.,  536.,  644., 1360.,  986., 1232.,
       2288., 1531., 1230., 1015., 1037., 1142., 1262., 1972.,  836.,
        881.,  876., 2146., 1557.,  800., 1196.,  652.,  494.,  651.,
        241.,  683.,  913., 1173.,  236.,  816.,  624., 1294.,  379.,
       2158.,  682., 1430.,  771.,  410.,   54.,  516.,   52.,   36.,
        331.,   68.,  660.,  864.,  544.,  140., 1733.,  601.,  962.,
        507.,  549., 1252.,  121.,  560.,  553.,  955.,  432.,  403.,
        625.,  310.,  998.,  388.,  568.,  100., 1312., 1387.,  708.,
        172.,  155.,  490.,  700.,  931.,  699.,  390.,  384.,  872.,
        745.,  546.,  621.,  630.,  433.,  120.,  941.,  826.,  633.,
        421.,  220.,  273.,  134.,  522.,  169.,  749., 1200., 1152.,
        527.,  456.,  257.,  342.,  173.,  552.,  460.,   70., 1094.,
        820., 1021., 1104., 1359.,  902.,  755.,  950.,  606., 1259.,
        710., 1234., 1246., 1111., 1478.,  399.,  547.,  332., 1078.,
        626.,  728.,  793.,  246.,  154.,   65.,  312.,  784.,  471.,
        454.,  803., 1476.,  445.,  767.,  841.,   55., 1758., 1115.,
        462.,  904., 1640.,  594.,  720.,  114.,  718.,  330.,  496.,
        706.,  851.,  138.,  450.,  656.,  504.,  319., 1337., 1034.,
        983., 1206.,  890.,  988., 1023.,  252.,  119.,  483.,  350.,
        286.,  378., 1012., 1728., 1375., 1420., 1082., 1249.,   40.,
       2257., 1149., 1075.,  372.,   20., 1204.,  846., 1073., 1087.,
       1660.,  228., 1096.,  729.,  666.,   80.,  362.,  537.,  472.,
        397.,   53.,  764.,  489.,  190.,  520.,  550., 1027., 1004.,
       1141.,  681.,  612.,  813.,  128., 1044.,  828.,  301.,  603.,
        732.,  260.,  583.,  658.,   32.,  531.,  575., 1053.,  958.,
        774.,  148.,  744.,  697.,  315.,  673.,  370.,   96.,  590.,
        116.,  234.,  200.,  406.,  175.,  521.,  201.,   nan,  203.,
        196.,  758.,  221., 1300.,  634.,  776.,  336.,  599., 1035.,
        324.,  779., 1271.,  355., 2085., 1153.,  770.,  262.,  722.,
       1308.,  688.,  663.,  781.,   88., 1194., 1538.,  662., 1593.,
         56.,  609., 1033.,  224.,  281.,  210., 1116.,  366.,  299.,
       1474., 1383.,  893., 1036.,  920., 1029., 1223., 1011., 1571.,
       1309.,  865.,  769.,  318.,  501.,  437.,  785.,  358.,  534.,
        638.,  647.,  838.,  186.,  871.,  414.,  248.,  926., 1101.,
       1047.,  797., 1558.,  256.,  321., 1328.,  903.,  492.,  566.,
         81.,  314.,  930.,  632.,  725., 1151., 1518., 1304., 1812.,
       1684.,  778.,  938.,  669., 1178.,  866., 1030.,  762.,  848.,
       1000.,  918., 1084.,  574., 1181., 1048.,  335., 1225., 1220.,
       1572.,  812.,  727.,  787.,  968.,   60.,  937.,  565.,  417.,
        901.,  457., 1732., 1632.,  973.,  910.,  346.,  819.,  792.,
        617.,  438.,  311.,  654., 1386.,  130.,  144.,  150.,  873.,
        908.,  668.,  512.,  408.,  441.,   85.,  595.,  292.,  242.,
        952.,  739., 1098.,  782.,  122.,  168.,  259.,  316.,  317.,
        351.,  354.,  485.,  925.,  513.,  249.,  748.,  216.,  386.,
        258.,  587.,  491.,  453.,  557., 1080.,  497.,  608.,   51.,
        539.,  420.,  502.,  671.,  385., 1412., 1198.,  709.,  132.,
        611., 4010.,  467.,   77.,  371.,  113.,  533.,  540.,  577.,
        434.,  548.,  967.,  737., 1573., 1001.,  585., 1392., 1239.,
        924.,  949.,  215., 1329.,  503., 1148., 1112.,  796.,  811.,
       1090.,  596.,  773., 1127., 1110.,  705., 1218.,  205., 1191.,
       1416., 1005.,  951.,  402.,  282.,  382.,  373., 1369., 1505.,
       1290.,  880.,  994.,  415., 1038.,  505., 1182.,  380.,  247.,
       1562., 1836.,  278.,  554.,  162.,  181.,  712.,  659., 1118.,
        361.,  760.,  799.,  996.,  486.,  939.,  623.,  678.,  914.,
        824.,  271.,  488., 1018.,  338.,  580.,  701.,  455.,  809.,
        953.,  381.,  208.,  143.,  576.,  416.,  347.,  510.,  194.,
        794.,  810.,  535.,  230.,  425.,  261.,  393., 1576., 1122.,
        853.,  894.,  509.,  639.,  685.,  976.,  475.,  691.,  424.,
        305.,  646.,  526.,  374., 1564.,  909., 1136., 1350., 1455.,
       1243.,  149., 1224.,  337.])

In [260]:
df_copy[column].fillna(value=0, inplace=True)

In [261]:
df_copy[column].unique()

array([ 468.,  923.,  791.,  602.,  263.,    0.,  935.,  637.,  804.,
       1051.,  156.,  300.,  514.,  110.,   28., 1373.,  578.,   24.,
         16.,  326., 1414.,  126.,  250., 1129., 1298.,  280.,  368.,
        376.,  466.,  244., 1032.,  484.,  833.,  506., 1137.,  687.,
        329.,  698., 1059., 1010., 1500.,  670.,  944., 1188.,  856.,
        936.,  734.,  339.,  648.,  532.,  481.,  588.,  717.,   48.,
        579.,  274.,  780.,  176.,  283.,  788.,  474.,  188.,  452.,
        264.,  360.,  276.,  448.,  960.,  766., 1026.,   73.,  736.,
        704.,  240.,  775., 1319.,  267., 1092.,  964.,  288.,  104.,
        192.,  954., 1346., 1433.,  860.,  870.,  353.,  198.,  480.,
       1682.,  672., 1070.,  528.,  133.,  238.,  426.,  375.,  343.,
        747.,   76.,  308.,  615.,  679.,   78.,   42.,  915.,  294.,
        469.,  207.,  458.,  476., 1341.,  564.,  844.,  847.,  850.,
        284., 1965.,  341.,  741.,  189.,  600.,  400.,  363.,  832.,
        622.,  225., 1333.,  888.,  636.,  500.,  726.,  254.,  306.,
        435.,  389.,  320.,  279.,  536.,  644., 1360.,  986., 1232.,
       2288., 1531., 1230., 1015., 1037., 1142., 1262., 1972.,  836.,
        881.,  876., 2146., 1557.,  800., 1196.,  652.,  494.,  651.,
        241.,  683.,  913., 1173.,  236.,  816.,  624., 1294.,  379.,
       2158.,  682., 1430.,  771.,  410.,   54.,  516.,   52.,   36.,
        331.,   68.,  660.,  864.,  544.,  140., 1733.,  601.,  962.,
        507.,  549., 1252.,  121.,  560.,  553.,  955.,  432.,  403.,
        625.,  310.,  998.,  388.,  568.,  100., 1312., 1387.,  708.,
        172.,  155.,  490.,  700.,  931.,  699.,  390.,  384.,  872.,
        745.,  546.,  621.,  630.,  433.,  120.,  941.,  826.,  633.,
        421.,  220.,  273.,  134.,  522.,  169.,  749., 1200., 1152.,
        527.,  456.,  257.,  342.,  173.,  552.,  460.,   70., 1094.,
        820., 1021., 1104., 1359.,  902.,  755.,  950.,  606., 1259.,
        710., 1234., 1246., 1111., 1478.,  399.,  547.,  332., 1078.,
        626.,  728.,  793.,  246.,  154.,   65.,  312.,  784.,  471.,
        454.,  803., 1476.,  445.,  767.,  841.,   55., 1758., 1115.,
        462.,  904., 1640.,  594.,  720.,  114.,  718.,  330.,  496.,
        706.,  851.,  138.,  450.,  656.,  504.,  319., 1337., 1034.,
        983., 1206.,  890.,  988., 1023.,  252.,  119.,  483.,  350.,
        286.,  378., 1012., 1728., 1375., 1420., 1082., 1249.,   40.,
       2257., 1149., 1075.,  372.,   20., 1204.,  846., 1073., 1087.,
       1660.,  228., 1096.,  729.,  666.,   80.,  362.,  537.,  472.,
        397.,   53.,  764.,  489.,  190.,  520.,  550., 1027., 1004.,
       1141.,  681.,  612.,  813.,  128., 1044.,  828.,  301.,  603.,
        732.,  260.,  583.,  658.,   32.,  531.,  575., 1053.,  958.,
        774.,  148.,  744.,  697.,  315.,  673.,  370.,   96.,  590.,
        116.,  234.,  200.,  406.,  175.,  521.,  201.,  203.,  196.,
        758.,  221., 1300.,  634.,  776.,  336.,  599., 1035.,  324.,
        779., 1271.,  355., 2085., 1153.,  770.,  262.,  722., 1308.,
        688.,  663.,  781.,   88., 1194., 1538.,  662., 1593.,   56.,
        609., 1033.,  224.,  281.,  210., 1116.,  366.,  299., 1474.,
       1383.,  893., 1036.,  920., 1029., 1223., 1011., 1571., 1309.,
        865.,  769.,  318.,  501.,  437.,  785.,  358.,  534.,  638.,
        647.,  838.,  186.,  871.,  414.,  248.,  926., 1101., 1047.,
        797., 1558.,  256.,  321., 1328.,  903.,  492.,  566.,   81.,
        314.,  930.,  632.,  725., 1151., 1518., 1304., 1812., 1684.,
        778.,  938.,  669., 1178.,  866., 1030.,  762.,  848., 1000.,
        918., 1084.,  574., 1181., 1048.,  335., 1225., 1220., 1572.,
        812.,  727.,  787.,  968.,   60.,  937.,  565.,  417.,  901.,
        457., 1732., 1632.,  973.,  910.,  346.,  819.,  792.,  617.,
        438.,  311.,  654., 1386.,  130.,  144.,  150.,  873.,  908.,
        668.,  512.,  408.,  441.,   85.,  595.,  292.,  242.,  952.,
        739., 1098.,  782.,  122.,  168.,  259.,  316.,  317.,  351.,
        354.,  485.,  925.,  513.,  249.,  748.,  216.,  386.,  258.,
        587.,  491.,  453.,  557., 1080.,  497.,  608.,   51.,  539.,
        420.,  502.,  671.,  385., 1412., 1198.,  709.,  132.,  611.,
       4010.,  467.,   77.,  371.,  113.,  533.,  540.,  577.,  434.,
        548.,  967.,  737., 1573., 1001.,  585., 1392., 1239.,  924.,
        949.,  215., 1329.,  503., 1148., 1112.,  796.,  811., 1090.,
        596.,  773., 1127., 1110.,  705., 1218.,  205., 1191., 1416.,
       1005.,  951.,  402.,  282.,  382.,  373., 1369., 1505., 1290.,
        880.,  994.,  415., 1038.,  505., 1182.,  380.,  247., 1562.,
       1836.,  278.,  554.,  162.,  181.,  712.,  659., 1118.,  361.,
        760.,  799.,  996.,  486.,  939.,  623.,  678.,  914.,  824.,
        271.,  488., 1018.,  338.,  580.,  701.,  455.,  809.,  953.,
        381.,  208.,  143.,  576.,  416.,  347.,  510.,  194.,  794.,
        810.,  535.,  230.,  425.,  261.,  393., 1576., 1122.,  853.,
        894.,  509.,  639.,  685.,  976.,  475.,  691.,  424.,  305.,
        646.,  526.,  374., 1564.,  909., 1136., 1350., 1455., 1243.,
        149., 1224.,  337.])

## Categorize `BsmtFinType2`

* 7->`NA`: No Basement

In [262]:
column = 'BsmtFinType2'

In [263]:
df_copy[column].unique()

array([ 5.,  1.,  4.,  2.,  6.,  3., nan])

In [264]:
df_copy[column].fillna(value=7, inplace=True)

In [265]:
df_copy[column].unique()

array([5., 1., 4., 2., 6., 3., 7.])

## Categorize `BsmtFinSF2`

* 0 ->`NA`: No Basement

In [266]:
column = 'BsmtFinSF2'

In [267]:
df_copy[column].unique()

array([ 144.,    0.,   78.,  859.,  981.,   42.,   46.,  162.,  174.,
        350.,  263., 1073.,   12.,  159.,  474.,  453.,  684.,  387.,
        688.,  252.,  590.,  284.,  276.,  168.,  294.,  622.,  113.,
       1526.,  360.,  774.,  364.,  596.,  884.,   92.,  216.,  136.,
        147.,  201.,  512.,  247.,  202.,  483.,  750.,   60.,  102.,
         95.,   63.,  262.,  393.,  286.,  450.,   72.,  243.,  694.,
        875.,  507.,  435.,  419.,  250.,  116.,  624.,   76.,  270.,
        110.,  288.,  186.,  449.,   48.,  613.,  495.,  852.,  555.,
        799.,  811.,  842.,  670.,  382.,  456.,  308.,   52.,  196.,
        128.,  488.,  319.,  273.,   nan,  240.,  956.,  723.,  120.,
        679.,   40.,  121.,  604.,  153.,  619.,    6.,  351., 1037.,
        829.,  264.,   38.,  206.,  167.,  543.,  259.,  404.,  138.,
        955.,  691.,  354.,   66.,  154.,  442.,  448.,  210.,  227.,
        398.,  127.,  722.,  761.,  529.,  522.,  873.,  891.,  755.,
        321.,  915.,  417.,  432.,  465.,  841.,  105.,  831.,  278.,
       1020.,  530.,   80.,  904.,  539.,  620.,  156.,  108.,  492.,
       1393., 1039.,  497.,   68.,  402.,  748.,  281.,  912.,  373.,
        982.,  826.,  850., 1164., 1083.,  400.,  337.,  297.,  344.])

In [268]:
df_copy[column].fillna(value=0, inplace=True)

In [269]:
df_copy[column].unique()

array([ 144.,    0.,   78.,  859.,  981.,   42.,   46.,  162.,  174.,
        350.,  263., 1073.,   12.,  159.,  474.,  453.,  684.,  387.,
        688.,  252.,  590.,  284.,  276.,  168.,  294.,  622.,  113.,
       1526.,  360.,  774.,  364.,  596.,  884.,   92.,  216.,  136.,
        147.,  201.,  512.,  247.,  202.,  483.,  750.,   60.,  102.,
         95.,   63.,  262.,  393.,  286.,  450.,   72.,  243.,  694.,
        875.,  507.,  435.,  419.,  250.,  116.,  624.,   76.,  270.,
        110.,  288.,  186.,  449.,   48.,  613.,  495.,  852.,  555.,
        799.,  811.,  842.,  670.,  382.,  456.,  308.,   52.,  196.,
        128.,  488.,  319.,  273.,  240.,  956.,  723.,  120.,  679.,
         40.,  121.,  604.,  153.,  619.,    6.,  351., 1037.,  829.,
        264.,   38.,  206.,  167.,  543.,  259.,  404.,  138.,  955.,
        691.,  354.,   66.,  154.,  442.,  448.,  210.,  227.,  398.,
        127.,  722.,  761.,  529.,  522.,  873.,  891.,  755.,  321.,
        915.,  417.,  432.,  465.,  841.,  105.,  831.,  278., 1020.,
        530.,   80.,  904.,  539.,  620.,  156.,  108.,  492., 1393.,
       1039.,  497.,   68.,  402.,  748.,  281.,  912.,  373.,  982.,
        826.,  850., 1164., 1083.,  400.,  337.,  297.,  344.])

## Categorize `BsmtUnfSF`

* 0 ->`NA`: No Basement

In [270]:
column = 'BsmtUnfSF'

In [271]:
df_copy[column].unique()

array([ 270.,  406.,  137.,  324., 1017.,  763.,  233.,  789.,  663.,
          0.,  354.,  327.,  225.,  341.,  836., 1590., 1544., 1588.,
       1794., 1473., 1093., 1346., 1324., 1129.,   58.,  847., 1629.,
       1595., 1218.,   54.,  831.,  816.,  223.,  261.,  190.,  840.,
        320.,  224.,  290.,  286.,  610.,  491.,  659., 1323.,  143.,
        386.,  534.,  150.,  500.,  533.,  228.,  470.,  482.,  136.,
       1604.,  292.,  125.,  510.,  832.,  525.,  456.,  576.,  161.,
        237.,  415.,  661.,  357.,  827.,  247.,  678.,  930.,  346.,
        455.,  200.,  634.,  577.,  144.,  308.,  316.,  480.,  252.,
        164.,  888.,  780.,  662.,  656.,  689.,  186.,  232.,  120.,
       1128.,   89.,  328.,  660.,  153.,  172.,  564.,  218.,  162.,
       1250.,   86., 1198.,  676.,  140.,  396.,  296., 1040.,  176.,
        381.,  126.,  744.,  960.,  974.,  618.,  894.,  850.,  657.,
         80.,  235., 1115.,  321.,  756.,  221.,  434., 1958., 1258.,
       1214.,  384., 1026., 1430., 1344.,   30.,  370.,  546.,  395.,
         36., 1216.,  166.,  388.,  208.,  318.,  590.,   98.,  158.,
        100.,  243., 1077.,  846.,  195.,  476.,  107., 1181.,  722.,
       1064.,  441.,  304., 1058.,  471.,  540., 1180.,  543.,  138.,
        624.,  229.,   79.,  498.,  466.,  484.,  300.,  220.,  416.,
        379.,  788.,  342., 1736.,  251.,  278.,  724.,  467.,  632.,
       1082., 1598.,  522.,  425.,  474.,  643., 1084., 1451.,  516.,
       1405.,  728.,  745., 1204.,  868.,  130.,  204.,  219.,  111.,
        264.,  282.,  262.,  254.,  549., 1696., 1614.,  408., 1043.,
       1436., 1402., 1530., 1348., 1836.,  222.,  422.,  402., 1087.,
       1158.,  835., 1114., 1450.,  276.,  400., 1332.,  122.,  345.,
         28.,  288.,  182.,  189., 1376., 1726.,  183.,  249.,  142.,
        306., 1619.,  392.,  932.,  588.,  216., 1568.,  160.,  461.,
        265.,  294.,  356.,  640.,  613.,  507.,  141.,  175.,  313.,
        785.,  280.,  565.,  727.,  295., 1866.,  572.,  323.,   93.,
        810.,  792.,  405., 1054., 1313.,  560.,  720.,  630., 1248.,
        996.,  108.,  206.,  559.,  174., 1041.,  901.,  339.,  240.,
        504.,  269.,  600.,  801.,  861.,  677.,  917.,  972.,  741.,
        245., 1022.,  297.,  248.,  679.,  938., 1048.,  672.,  198.,
        483.,  851.,   46.,  585.,  552.,  550.,  825.,  916.,  104.,
        605.,  348.,  616., 1468.,  479.,  380.,  382., 1474.,  704.,
        649.,  513.,  322.,  132.,  335., 1068.,  944.,  462.,  608.,
        615.,  301., 1678.,  604.,   94.,  583.,  112.,  674.,  621.,
         91.,   90.,  561.,  118.,  581.,  760.,  412.,  135., 1527.,
        432.,  526.,  250.,  117.,  912.,  338.,  594.,   75.,  778.,
        898., 1008., 1280.,  332., 1018., 1152.,  547., 1632., 1488.,
        692.,  469.,  273.,  738.,  440., 1444.,  213.,  896.,  684.,
         25.,  275.,  570.,  575.,  430.,  538.,  165.,  908.,  454.,
        404., 1765., 1486., 1347.,  596.,  496., 1318.,  764., 1146.,
        438.,  707.,  167., 1173., 1519., 1242., 1341.,  226.,  794.,
       1339., 1660., 1095., 1162.,  284.,  355.,  439.,  375., 1328.,
       1211.,  210.,  194.,  587.,   72.,  177.,  147.,  584.,  952.,
        599., 1439.,  723., 1625.,  196., 1728.,  242.,  638.,  505.,
        529.,  503.,  437.,  330.,  998., 1824.,  747.,  892.,  168.,
        675.,  444.,  188.,  453.,  936.,  181., 1800.,  398., 1117.,
         96.,  680.,  828.,  931.,  481.,  459.,  407.,  448.,  797.,
        508.,  739.,  784.,  869.,  329.,  849.,  554.,  460.,  949.,
        475.,  992.,  497.,   nan,  449.,  897., 1046.,  796.,  768.,
       1272.,  880.,  647.,  451.,  536.,  197.,  234.,  852.,  326.,
        212.,  925.,  545.,  639.,  298.,  331.,  457.,  628., 1615.,
        598.,  631.,  268.,  110.,  255.,   83.,  782.,  180., 1257.,
        163., 1421., 1508., 1327.,  541.,  725., 1228.,  336.,  884.,
        591.,  397.,  555.,  367.,  520.,  821.,  173.,  592., 1140.,
        910.,  352., 1495.,  403.,  443.,  873.,  393.,   35., 1092.,
        325.,   88.,  271.,  207.,  217.,  686.,  749.,   52.,  277.,
       1168.,  903.,  752.,  918., 1559.,   53.,  815., 1028.,  201.,
         22.,  372., 1012.,  359.,  214., 1337.,  423.,  263., 1694.,
       1108.,  740., 1704.,  636., 1582., 1802., 1706.,  436., 1602.,
       1298.,  272.,  729., 1300.,  698., 1246., 1266.,   56.,  192.,
       1510.,  941.,  736., 1066.,  770., 1369., 1496.,  394., 1528.,
        769.,  716.,  982., 1302., 1314., 1335., 1574., 1685., 1100.,
       1143.,  365., 1461.,   76.,  527., 1081., 1550.,  179.,  319.,
        385., 1594.,  171.,  548.,  431.,  433.,  710., 1560.,  191.,
         63.,  765., 1144.,  410.,  424.,  928.,  156.,  666.,   55.,
        312.,  569.,  967.,  808., 1075.,  667.,  371.,  819.,  809.,
        966.,  750.,  969.,  366.,  771.,  717.,  187.,  635.,   20.,
        420.,  231.,   95.,  109.,  486.,  935.,  411.,  951., 1105.,
       1643., 2140., 1526., 1453., 1270.,  879.,  472.,  646.,  215.,
        845.,  501.,  399.,  102.,  193.,  860.,  683.,  333.,  426.,
       1330.,  115., 1179.,  123., 1085., 1195.,  238.,  971.,  285.,
       1680.,  427., 1262.,  279.,  311.,  957.,  106.,  856.,   17.,
       1689.,  963.,  970.,  593., 1491.,   27.,   48.,  185.,  490.,
        595., 1851.,  113.,  781., 1074., 1640., 2062., 1191.,  889.,
        644., 1390.,  523.,  494.,  945.,   42.,  127.,  363.,  369.,
       1618., 1721., 1090., 1209., 1088., 1251., 1326., 1052.,  767.,
       1126.,  848., 1035.,  253.,  655.,  358.,  742., 1504., 1254.,
        858., 1118., 1400., 1131.,  891.,   78.,  939.,  362.,  450.,
        530.,  713.,  293.,   34.,  360., 1404.,   60., 1584.,  307.,
        556.,   99.,  350.,  517.,  929.,  521., 1153.,  715.,  802.,
       1556.,  236.,  863.,  502.,  817.,  844.,  798., 1226., 1020.,
        641.,  477., 1921.,  830., 1967., 1466.,  872.,   33., 1411.,
       1057.,  532., 1308.,  260., 1558.,  535.,  579.,   57.,  170.,
       1065.,  258.,  131.,  390.,  340., 1150.,  864.,  128.,  818.,
        299.,  637.,  697.,  671.,  487., 1664.,  129.,  378.,  383.,
         45., 1503.])

In [272]:
df_copy[column].fillna(value=0, inplace=True)

In [273]:
df_copy[column].unique()

array([ 270.,  406.,  137.,  324., 1017.,  763.,  233.,  789.,  663.,
          0.,  354.,  327.,  225.,  341.,  836., 1590., 1544., 1588.,
       1794., 1473., 1093., 1346., 1324., 1129.,   58.,  847., 1629.,
       1595., 1218.,   54.,  831.,  816.,  223.,  261.,  190.,  840.,
        320.,  224.,  290.,  286.,  610.,  491.,  659., 1323.,  143.,
        386.,  534.,  150.,  500.,  533.,  228.,  470.,  482.,  136.,
       1604.,  292.,  125.,  510.,  832.,  525.,  456.,  576.,  161.,
        237.,  415.,  661.,  357.,  827.,  247.,  678.,  930.,  346.,
        455.,  200.,  634.,  577.,  144.,  308.,  316.,  480.,  252.,
        164.,  888.,  780.,  662.,  656.,  689.,  186.,  232.,  120.,
       1128.,   89.,  328.,  660.,  153.,  172.,  564.,  218.,  162.,
       1250.,   86., 1198.,  676.,  140.,  396.,  296., 1040.,  176.,
        381.,  126.,  744.,  960.,  974.,  618.,  894.,  850.,  657.,
         80.,  235., 1115.,  321.,  756.,  221.,  434., 1958., 1258.,
       1214.,  384., 1026., 1430., 1344.,   30.,  370.,  546.,  395.,
         36., 1216.,  166.,  388.,  208.,  318.,  590.,   98.,  158.,
        100.,  243., 1077.,  846.,  195.,  476.,  107., 1181.,  722.,
       1064.,  441.,  304., 1058.,  471.,  540., 1180.,  543.,  138.,
        624.,  229.,   79.,  498.,  466.,  484.,  300.,  220.,  416.,
        379.,  788.,  342., 1736.,  251.,  278.,  724.,  467.,  632.,
       1082., 1598.,  522.,  425.,  474.,  643., 1084., 1451.,  516.,
       1405.,  728.,  745., 1204.,  868.,  130.,  204.,  219.,  111.,
        264.,  282.,  262.,  254.,  549., 1696., 1614.,  408., 1043.,
       1436., 1402., 1530., 1348., 1836.,  222.,  422.,  402., 1087.,
       1158.,  835., 1114., 1450.,  276.,  400., 1332.,  122.,  345.,
         28.,  288.,  182.,  189., 1376., 1726.,  183.,  249.,  142.,
        306., 1619.,  392.,  932.,  588.,  216., 1568.,  160.,  461.,
        265.,  294.,  356.,  640.,  613.,  507.,  141.,  175.,  313.,
        785.,  280.,  565.,  727.,  295., 1866.,  572.,  323.,   93.,
        810.,  792.,  405., 1054., 1313.,  560.,  720.,  630., 1248.,
        996.,  108.,  206.,  559.,  174., 1041.,  901.,  339.,  240.,
        504.,  269.,  600.,  801.,  861.,  677.,  917.,  972.,  741.,
        245., 1022.,  297.,  248.,  679.,  938., 1048.,  672.,  198.,
        483.,  851.,   46.,  585.,  552.,  550.,  825.,  916.,  104.,
        605.,  348.,  616., 1468.,  479.,  380.,  382., 1474.,  704.,
        649.,  513.,  322.,  132.,  335., 1068.,  944.,  462.,  608.,
        615.,  301., 1678.,  604.,   94.,  583.,  112.,  674.,  621.,
         91.,   90.,  561.,  118.,  581.,  760.,  412.,  135., 1527.,
        432.,  526.,  250.,  117.,  912.,  338.,  594.,   75.,  778.,
        898., 1008., 1280.,  332., 1018., 1152.,  547., 1632., 1488.,
        692.,  469.,  273.,  738.,  440., 1444.,  213.,  896.,  684.,
         25.,  275.,  570.,  575.,  430.,  538.,  165.,  908.,  454.,
        404., 1765., 1486., 1347.,  596.,  496., 1318.,  764., 1146.,
        438.,  707.,  167., 1173., 1519., 1242., 1341.,  226.,  794.,
       1339., 1660., 1095., 1162.,  284.,  355.,  439.,  375., 1328.,
       1211.,  210.,  194.,  587.,   72.,  177.,  147.,  584.,  952.,
        599., 1439.,  723., 1625.,  196., 1728.,  242.,  638.,  505.,
        529.,  503.,  437.,  330.,  998., 1824.,  747.,  892.,  168.,
        675.,  444.,  188.,  453.,  936.,  181., 1800.,  398., 1117.,
         96.,  680.,  828.,  931.,  481.,  459.,  407.,  448.,  797.,
        508.,  739.,  784.,  869.,  329.,  849.,  554.,  460.,  949.,
        475.,  992.,  497.,  449.,  897., 1046.,  796.,  768., 1272.,
        880.,  647.,  451.,  536.,  197.,  234.,  852.,  326.,  212.,
        925.,  545.,  639.,  298.,  331.,  457.,  628., 1615.,  598.,
        631.,  268.,  110.,  255.,   83.,  782.,  180., 1257.,  163.,
       1421., 1508., 1327.,  541.,  725., 1228.,  336.,  884.,  591.,
        397.,  555.,  367.,  520.,  821.,  173.,  592., 1140.,  910.,
        352., 1495.,  403.,  443.,  873.,  393.,   35., 1092.,  325.,
         88.,  271.,  207.,  217.,  686.,  749.,   52.,  277., 1168.,
        903.,  752.,  918., 1559.,   53.,  815., 1028.,  201.,   22.,
        372., 1012.,  359.,  214., 1337.,  423.,  263., 1694., 1108.,
        740., 1704.,  636., 1582., 1802., 1706.,  436., 1602., 1298.,
        272.,  729., 1300.,  698., 1246., 1266.,   56.,  192., 1510.,
        941.,  736., 1066.,  770., 1369., 1496.,  394., 1528.,  769.,
        716.,  982., 1302., 1314., 1335., 1574., 1685., 1100., 1143.,
        365., 1461.,   76.,  527., 1081., 1550.,  179.,  319.,  385.,
       1594.,  171.,  548.,  431.,  433.,  710., 1560.,  191.,   63.,
        765., 1144.,  410.,  424.,  928.,  156.,  666.,   55.,  312.,
        569.,  967.,  808., 1075.,  667.,  371.,  819.,  809.,  966.,
        750.,  969.,  366.,  771.,  717.,  187.,  635.,   20.,  420.,
        231.,   95.,  109.,  486.,  935.,  411.,  951., 1105., 1643.,
       2140., 1526., 1453., 1270.,  879.,  472.,  646.,  215.,  845.,
        501.,  399.,  102.,  193.,  860.,  683.,  333.,  426., 1330.,
        115., 1179.,  123., 1085., 1195.,  238.,  971.,  285., 1680.,
        427., 1262.,  279.,  311.,  957.,  106.,  856.,   17., 1689.,
        963.,  970.,  593., 1491.,   27.,   48.,  185.,  490.,  595.,
       1851.,  113.,  781., 1074., 1640., 2062., 1191.,  889.,  644.,
       1390.,  523.,  494.,  945.,   42.,  127.,  363.,  369., 1618.,
       1721., 1090., 1209., 1088., 1251., 1326., 1052.,  767., 1126.,
        848., 1035.,  253.,  655.,  358.,  742., 1504., 1254.,  858.,
       1118., 1400., 1131.,  891.,   78.,  939.,  362.,  450.,  530.,
        713.,  293.,   34.,  360., 1404.,   60., 1584.,  307.,  556.,
         99.,  350.,  517.,  929.,  521., 1153.,  715.,  802., 1556.,
        236.,  863.,  502.,  817.,  844.,  798., 1226., 1020.,  641.,
        477., 1921.,  830., 1967., 1466.,  872.,   33., 1411., 1057.,
        532., 1308.,  260., 1558.,  535.,  579.,   57.,  170., 1065.,
        258.,  131.,  390.,  340., 1150.,  864.,  128.,  818.,  299.,
        637.,  697.,  671.,  487., 1664.,  129.,  378.,  383.,   45.,
       1503.])

## Categorize `TotalBsmtSF`

* 0 ->`NA`: No Basement

In [274]:
column = 'TotalBsmtSF'

In [275]:
df_copy[column].unique()

array([ 882., 1329.,  928.,  926., 1280.,  763., 1168.,  789., 1300.,
       1405.,  483.,  525.,  855.,  836., 1590., 1544., 1698., 1822.,
       2846., 1671., 1370., 1324., 1145.,  384.,  847., 1629., 1595.,
       1218., 1468.,  831.,  816., 1208., 1231., 1390., 1488.,  840.,
        600.,  756.,  530., 1642.,  975., 1492., 1829., 1224.,  715.,
       1232., 1209., 1510.,  533., 1728., 1140.,  782., 1080., 1604.,
       1480., 1143., 1206., 1244.,  832.,  864.,  972.,  988.,  576.,
       1175., 1395.,  709.,  936., 1347.,  827., 1027., 1008.,  678.,
        930.,  346.,  738., 1108.,  765.,  608.,  572.,  835.,  780.,
        528., 1124.,  888.,  662., 1422.,  689., 1212.,  707.,  856.,
       1832., 1319.,  720., 1420.,  660., 1117.,  663., 1172., 1508.,
       1250., 1433.,  946., 1222.,  676.,  870.,  878., 1026.,  876.,
       1978., 1040.,  848.,    0.,  381., 1196.,  744.,  960., 1107.,
        894., 1528., 1032.,  423.,  982., 1191.,  480.,  629., 1594.,
       1049., 1243., 1958., 1336., 1214., 1068., 1430., 1344.,  945.,
        546.,  833., 1216.,  624., 1679., 1152., 1434., 2208., 1418.,
       1587.,  952., 1181., 1122., 1427., 1043., 1058., 1621., 1116.,
       1176., 1180.,  804., 1057., 1776., 1365., 2020., 2630., 1736.,
       1782., 1739., 1504., 1774., 1760., 2452., 1082., 1598., 1358.,
       1306., 1350., 2492., 2200., 1884., 1451., 1712.,  728.,  745.,
       1220.,  868.,  846.,  698.,  794., 1177., 1455., 2024., 1070.,
       1173., 1696., 1614., 1702., 2458., 1436., 1402., 1530., 1372.,
        900., 1836., 1652., 1553.,  812., 1141., 1158., 1512., 1114.,
       1450.,  913., 1332.,  754.,  980., 1024.,  912., 2014., 1376.,
       1726.,  691., 1694., 1740.,  392.,  752.,  932., 1288.,  908.,
       1568., 1165., 1048., 1313., 1292., 1680., 1453., 1562., 1169.,
       1202., 1382., 1200., 1866., 1062.,  631.,  793., 1031.,  699.,
        792.,  405., 1054.,  560.,  416.,  630., 1248., 1380.,  951.,
       1105.,  160.,  795., 1041.,  732.,  941., 1045.,  901.,  240.,
        504.,  690.,  801.,  768.,  861.,  677.,  917.,  741.,  245.,
       1022.,  297.,  468., 1072.,  672., 1020., 1204.,  858.,  585.,
       1052.,  456.,  552., 1138.,  825., 1073.,  747., 1089.,  520.,
       1079., 1094., 1555., 1720., 1838., 1282., 1254., 1498.,  704.,
       1449.,  990., 1463., 1431.,  907.,  914., 1569.,  944., 1462.,
       1417., 1578., 1014.,  547., 1078., 1678., 1150.,  583., 1273.,
        920., 1112., 1561., 1067., 1310.,  516.,  561., 1803.,  760.,
       1596.,  902.,  957., 1582., 2190., 1641.,  712., 1645., 1188.,
        796.,  828.,  784.,  680.,  916., 1348., 1664., 1337., 1632.,
       1710., 1675., 1260., 2048., 1211., 1444., 1236.,  896., 1055.,
       2418., 1950., 1850., 1620., 1414.,  948., 1148., 2535., 1603.,
       1479., 1765., 1858., 1367., 1800., 1342.,  764., 1415., 1393.,
       1146., 1037., 1519., 1982., 1064., 1242., 1341.,  955., 1460.,
       1363., 1660., 1162.,  886.,  984.,  890., 1001., 1848., 1235.,
       1419., 1557.,  970., 1230.,  994., 1426., 1625., 1118.,  348.,
       1296., 1036., 1104.,  998., 1824.,  892., 1312., 1081., 1256.,
        854.,  192.,  931.,  884.,  481.,  684.,  904.,  407.,  448.,
        797.,  973.,  723.,  869.,  554.,  981.,  949.,  739.,  992.,
        565.,   nan,  989., 1100.,  810., 1272.,  880.,  451.,  536.,
       1046.,  450., 1060., 1524.,  570., 1580., 1509.,  621., 1077.,
       1602.,  628., 1615., 2271., 1751., 1401., 1182., 1076., 1257.,
       1357., 1778., 1129.,  850., 1445., 1564., 1351., 1092., 1127.,
       1029.,  911., 1228.,  644.,  798.,  942., 1091., 1898., 1151.,
        173.,  356.,  592., 1840.,  910., 1277., 1518.,  352., 1495.,
       1432., 1666., 1964., 1189.,  550.,  526.,  462., 1113.,  845.,
        686.,  923.,  938.,  903., 1302., 1166., 1149., 2660., 1612.,
       2220., 1742., 1284.,  725., 1529., 1153., 1259., 1084.,  925.,
       1061., 1790., 2108., 1934., 1994., 2552., 1704., 2320.,  918.,
       1802., 1706., 1317.,  895., 1721., 1298., 1362., 1554., 1577.,
       1326., 1246., 1406., 1266.,  915., 1779., 1408., 1389., 1066.,
       1325., 1369., 1542., 1966., 1538., 1494., 1338., 1335., 1574.,
       1685., 1461., 1223., 1044., 1378., 1511., 1352., 1550., 1339.,
       2002., 2461., 1295., 1093.,  964., 1174., 1042., 1130., 1592.,
        822.,  666.,  370.,  808., 1560., 1053., 1144., 1331.,  922.,
       1190.,  924.,  736., 1170., 1377.,  967., 1075.,  616.,  687.,
        819.,  966.,  750.,  969.,  976.,  771., 1005.,  943., 1240.,
        671.,  409.,  484., 1038.,  779., 1643., 2140., 1546., 1489.,
       1270.,  879.,  929.,  635., 1097.,  853.,  985., 1015.,  995.,
        385., 1673.,  979.,  860., 1556., 1531., 1330., 1088., 1179.,
        734., 5095., 1195., 1290.,  651.,  531.,  851., 1004.,  279.,
        859.,  837., 1573., 1441., 1409., 1454.,  852., 1501., 1689.,
       1265., 1267., 1922., 1491., 1160.,  716., 1396., 1090., 1178.,
       1617., 1705., 1851.,  813.,  781.,  821., 1074., 1700., 2062.,
       1398., 1714., 1910., 1047.,  675., 1103., 1487.,  494., 1069.,
       1738., 1618., 1868., 1606., 1792., 1780., 1686., 1368., 1142.,
       1035., 1540., 1733., 1286., 1670., 1278., 2036., 1400., 1131.,
        891., 1217.,  636., 1748., 1334.,  569., 1051., 1187., 1251.,
       1056., 1584., 1121., 1050.,  216.,  301., 2171.,  713., 1083.,
       1135., 1438., 1025., 1147.,  502.,  844.,  492.,  770., 1226.,
        596.,  396.,  610.,  806., 1921.,  830., 1059., 1967., 1949.,
        872., 1865., 1000.,  430.,  799., 1308., 1570., 1388., 1425.,
        842.,  826., 1065.,  954.,  498.,  755.,  818.,  824.,  817.,
        637.,  697.,  432.,  641., 1128., 1381.,  264.,  996.])

In [276]:
df_copy[column].fillna(value=0, inplace=True)

In [277]:
df_copy[column].unique()

array([ 882., 1329.,  928.,  926., 1280.,  763., 1168.,  789., 1300.,
       1405.,  483.,  525.,  855.,  836., 1590., 1544., 1698., 1822.,
       2846., 1671., 1370., 1324., 1145.,  384.,  847., 1629., 1595.,
       1218., 1468.,  831.,  816., 1208., 1231., 1390., 1488.,  840.,
        600.,  756.,  530., 1642.,  975., 1492., 1829., 1224.,  715.,
       1232., 1209., 1510.,  533., 1728., 1140.,  782., 1080., 1604.,
       1480., 1143., 1206., 1244.,  832.,  864.,  972.,  988.,  576.,
       1175., 1395.,  709.,  936., 1347.,  827., 1027., 1008.,  678.,
        930.,  346.,  738., 1108.,  765.,  608.,  572.,  835.,  780.,
        528., 1124.,  888.,  662., 1422.,  689., 1212.,  707.,  856.,
       1832., 1319.,  720., 1420.,  660., 1117.,  663., 1172., 1508.,
       1250., 1433.,  946., 1222.,  676.,  870.,  878., 1026.,  876.,
       1978., 1040.,  848.,    0.,  381., 1196.,  744.,  960., 1107.,
        894., 1528., 1032.,  423.,  982., 1191.,  480.,  629., 1594.,
       1049., 1243., 1958., 1336., 1214., 1068., 1430., 1344.,  945.,
        546.,  833., 1216.,  624., 1679., 1152., 1434., 2208., 1418.,
       1587.,  952., 1181., 1122., 1427., 1043., 1058., 1621., 1116.,
       1176., 1180.,  804., 1057., 1776., 1365., 2020., 2630., 1736.,
       1782., 1739., 1504., 1774., 1760., 2452., 1082., 1598., 1358.,
       1306., 1350., 2492., 2200., 1884., 1451., 1712.,  728.,  745.,
       1220.,  868.,  846.,  698.,  794., 1177., 1455., 2024., 1070.,
       1173., 1696., 1614., 1702., 2458., 1436., 1402., 1530., 1372.,
        900., 1836., 1652., 1553.,  812., 1141., 1158., 1512., 1114.,
       1450.,  913., 1332.,  754.,  980., 1024.,  912., 2014., 1376.,
       1726.,  691., 1694., 1740.,  392.,  752.,  932., 1288.,  908.,
       1568., 1165., 1048., 1313., 1292., 1680., 1453., 1562., 1169.,
       1202., 1382., 1200., 1866., 1062.,  631.,  793., 1031.,  699.,
        792.,  405., 1054.,  560.,  416.,  630., 1248., 1380.,  951.,
       1105.,  160.,  795., 1041.,  732.,  941., 1045.,  901.,  240.,
        504.,  690.,  801.,  768.,  861.,  677.,  917.,  741.,  245.,
       1022.,  297.,  468., 1072.,  672., 1020., 1204.,  858.,  585.,
       1052.,  456.,  552., 1138.,  825., 1073.,  747., 1089.,  520.,
       1079., 1094., 1555., 1720., 1838., 1282., 1254., 1498.,  704.,
       1449.,  990., 1463., 1431.,  907.,  914., 1569.,  944., 1462.,
       1417., 1578., 1014.,  547., 1078., 1678., 1150.,  583., 1273.,
        920., 1112., 1561., 1067., 1310.,  516.,  561., 1803.,  760.,
       1596.,  902.,  957., 1582., 2190., 1641.,  712., 1645., 1188.,
        796.,  828.,  784.,  680.,  916., 1348., 1664., 1337., 1632.,
       1710., 1675., 1260., 2048., 1211., 1444., 1236.,  896., 1055.,
       2418., 1950., 1850., 1620., 1414.,  948., 1148., 2535., 1603.,
       1479., 1765., 1858., 1367., 1800., 1342.,  764., 1415., 1393.,
       1146., 1037., 1519., 1982., 1064., 1242., 1341.,  955., 1460.,
       1363., 1660., 1162.,  886.,  984.,  890., 1001., 1848., 1235.,
       1419., 1557.,  970., 1230.,  994., 1426., 1625., 1118.,  348.,
       1296., 1036., 1104.,  998., 1824.,  892., 1312., 1081., 1256.,
        854.,  192.,  931.,  884.,  481.,  684.,  904.,  407.,  448.,
        797.,  973.,  723.,  869.,  554.,  981.,  949.,  739.,  992.,
        565.,  989., 1100.,  810., 1272.,  880.,  451.,  536., 1046.,
        450., 1060., 1524.,  570., 1580., 1509.,  621., 1077., 1602.,
        628., 1615., 2271., 1751., 1401., 1182., 1076., 1257., 1357.,
       1778., 1129.,  850., 1445., 1564., 1351., 1092., 1127., 1029.,
        911., 1228.,  644.,  798.,  942., 1091., 1898., 1151.,  173.,
        356.,  592., 1840.,  910., 1277., 1518.,  352., 1495., 1432.,
       1666., 1964., 1189.,  550.,  526.,  462., 1113.,  845.,  686.,
        923.,  938.,  903., 1302., 1166., 1149., 2660., 1612., 2220.,
       1742., 1284.,  725., 1529., 1153., 1259., 1084.,  925., 1061.,
       1790., 2108., 1934., 1994., 2552., 1704., 2320.,  918., 1802.,
       1706., 1317.,  895., 1721., 1298., 1362., 1554., 1577., 1326.,
       1246., 1406., 1266.,  915., 1779., 1408., 1389., 1066., 1325.,
       1369., 1542., 1966., 1538., 1494., 1338., 1335., 1574., 1685.,
       1461., 1223., 1044., 1378., 1511., 1352., 1550., 1339., 2002.,
       2461., 1295., 1093.,  964., 1174., 1042., 1130., 1592.,  822.,
        666.,  370.,  808., 1560., 1053., 1144., 1331.,  922., 1190.,
        924.,  736., 1170., 1377.,  967., 1075.,  616.,  687.,  819.,
        966.,  750.,  969.,  976.,  771., 1005.,  943., 1240.,  671.,
        409.,  484., 1038.,  779., 1643., 2140., 1546., 1489., 1270.,
        879.,  929.,  635., 1097.,  853.,  985., 1015.,  995.,  385.,
       1673.,  979.,  860., 1556., 1531., 1330., 1088., 1179.,  734.,
       5095., 1195., 1290.,  651.,  531.,  851., 1004.,  279.,  859.,
        837., 1573., 1441., 1409., 1454.,  852., 1501., 1689., 1265.,
       1267., 1922., 1491., 1160.,  716., 1396., 1090., 1178., 1617.,
       1705., 1851.,  813.,  781.,  821., 1074., 1700., 2062., 1398.,
       1714., 1910., 1047.,  675., 1103., 1487.,  494., 1069., 1738.,
       1618., 1868., 1606., 1792., 1780., 1686., 1368., 1142., 1035.,
       1540., 1733., 1286., 1670., 1278., 2036., 1400., 1131.,  891.,
       1217.,  636., 1748., 1334.,  569., 1051., 1187., 1251., 1056.,
       1584., 1121., 1050.,  216.,  301., 2171.,  713., 1083., 1135.,
       1438., 1025., 1147.,  502.,  844.,  492.,  770., 1226.,  596.,
        396.,  610.,  806., 1921.,  830., 1059., 1967., 1949.,  872.,
       1865., 1000.,  430.,  799., 1308., 1570., 1388., 1425.,  842.,
        826., 1065.,  954.,  498.,  755.,  818.,  824.,  817.,  637.,
        697.,  432.,  641., 1128., 1381.,  264.,  996.])

## Categorize `BsmtFullBath`

* 0 ->`NA`: No Basement

In [278]:
column = 'BsmtFullBath'

In [279]:
df_copy[column].unique()

array([ 0.,  1.,  2.,  3., nan])

In [281]:
df_copy[column].fillna(value=0, inplace=True)

In [282]:
df_copy[column].unique()

array([0., 1., 2., 3.])

## Categorize `BsmtHalfBath`

* 0 ->`NA`: No Basement

In [283]:
column = 'BsmtHalfBath'

In [284]:
df_copy[column].unique()

array([ 0.,  1., nan,  2.])

In [285]:
df_copy[column].fillna(value=0, inplace=True)

In [286]:
df_copy[column].unique()

array([0., 1., 2.])

## `GarageType` -> `GarageYrBlt` -> `GarageFinish` -> `GarageQual` -> `GarageCond`

## Categorize `GarageType`

* 7->`NA`: No Garage

In [287]:
column = 'GarageType'

In [288]:
df_copy[column].unique()

array([ 1.,  2.,  3., nan,  5.,  6.,  4.])

In [289]:
df_copy[column].fillna(value=7, inplace=True)

In [290]:
df_copy[column].unique()

array([1., 2., 3., 7., 5., 6., 4.])

## Categorize `GarageYrBlt`

* 98->`NA`: No Garage

In [294]:
column = 'GarageYrBlt'

In [295]:
df_copy[column].unique()

array([5.100e+01, 1.900e+01, 3.400e+01, 4.000e+00, 7.900e+01, 6.000e+00,
       4.100e+01, 1.700e+01, 3.900e+01, 5.900e+01, 5.800e+01, 4.900e+01,
       1.200e+01, 1.000e+00, 2.100e+01, 1.400e+01, 7.000e+00, 2.600e+01,
       4.800e+01, 5.000e+00, 8.200e+01, 1.800e+01, 7.700e+01, 2.700e+01,
       3.800e+01,       nan, 7.500e+01, 7.400e+01, 2.800e+01, 4.600e+01,
       8.800e+01, 6.300e+01, 4.400e+01, 5.000e+01, 1.500e+01, 3.600e+01,
       5.300e+01, 2.500e+01, 8.700e+01, 4.700e+01, 1.300e+01, 8.900e+01,
       2.000e+01, 6.200e+01, 1.000e+01, 8.000e+00, 8.600e+01, 5.400e+01,
       6.000e+01, 4.500e+01, 1.917e+03, 7.300e+01, 7.600e+01, 5.600e+01,
       2.200e+01, 3.300e+01, 4.200e+01, 4.300e+01, 8.400e+01, 3.000e+01,
       8.100e+01, 5.500e+01, 1.896e+03, 2.000e+00, 2.400e+01, 2.300e+01,
       1.100e+01, 3.000e+00, 6.800e+01, 6.100e+01, 3.500e+01, 7.200e+01,
       2.900e+01, 7.000e+01, 6.400e+01, 3.700e+01, 7.800e+01, 1.600e+01,
       6.500e+01, 3.100e+01, 7.100e+01, 8.300e+01, 9.400e+01, 9.100e+01,
       3.200e+01, 6.600e+01, 6.900e+01, 8.500e+01, 6.700e+01, 4.000e+01,
       8.000e+01, 5.200e+01, 1.895e+03, 9.000e+01, 2.207e+03, 5.700e+01,
       1.943e+03, 1.919e+03])

In [300]:
df_copy[column].nunique()

97

In [301]:
df_copy[column].fillna(value=98, inplace=True)

In [302]:
df_copy[column].unique()

array([5.100e+01, 1.900e+01, 3.400e+01, 4.000e+00, 7.900e+01, 6.000e+00,
       4.100e+01, 1.700e+01, 3.900e+01, 5.900e+01, 5.800e+01, 4.900e+01,
       1.200e+01, 1.000e+00, 2.100e+01, 1.400e+01, 7.000e+00, 2.600e+01,
       4.800e+01, 5.000e+00, 8.200e+01, 1.800e+01, 7.700e+01, 2.700e+01,
       3.800e+01, 9.800e+01, 7.500e+01, 7.400e+01, 2.800e+01, 4.600e+01,
       8.800e+01, 6.300e+01, 4.400e+01, 5.000e+01, 1.500e+01, 3.600e+01,
       5.300e+01, 2.500e+01, 8.700e+01, 4.700e+01, 1.300e+01, 8.900e+01,
       2.000e+01, 6.200e+01, 1.000e+01, 8.000e+00, 8.600e+01, 5.400e+01,
       6.000e+01, 4.500e+01, 1.917e+03, 7.300e+01, 7.600e+01, 5.600e+01,
       2.200e+01, 3.300e+01, 4.200e+01, 4.300e+01, 8.400e+01, 3.000e+01,
       8.100e+01, 5.500e+01, 1.896e+03, 2.000e+00, 2.400e+01, 2.300e+01,
       1.100e+01, 3.000e+00, 6.800e+01, 6.100e+01, 3.500e+01, 7.200e+01,
       2.900e+01, 7.000e+01, 6.400e+01, 3.700e+01, 7.800e+01, 1.600e+01,
       6.500e+01, 3.100e+01, 7.100e+01, 8.300e+01, 9.400e+01, 9.100e+01,
       3.200e+01, 6.600e+01, 6.900e+01, 8.500e+01, 6.700e+01, 4.000e+01,
       8.000e+01, 5.200e+01, 1.895e+03, 9.000e+01, 2.207e+03, 5.700e+01,
       1.943e+03, 1.919e+03])

## Categorize `GarageFinish`

* 4->`NA`: No Garage

In [303]:
column = 'GarageFinish'

In [304]:
df_copy[column].unique()

array([ 2.,  3.,  1., nan])

In [305]:
df_copy[column].fillna(value=4, inplace=True)

In [306]:
df_copy[column].unique()

array([2., 3., 1., 4.])

## Categorize `GarageQual`

* 6->`NA`: No Garage

In [307]:
column = 'GarageQual'

In [308]:
df_copy[column].unique()

array([ 1., nan,  2.,  3.,  5.])

In [309]:
df_copy[column].fillna(value=6, inplace=True)

In [310]:
df_copy[column].unique()

array([1., 6., 2., 3., 5.])

## Categorize `GarageCond`

* 6->`NA`: No Garage

In [311]:
column = 'GarageCond'

In [312]:
df_copy[column].unique()

array([ 1., nan,  2.,  3.,  4.,  5.])

In [313]:
df_copy[column].fillna(value=6, inplace=True)

In [314]:
df_copy[column].unique()

array([1., 6., 2., 3., 4., 5.])

## GarageCars -> GarageArea

## Categorize `GarageCars`

* 0->`NA`: No Garage

In [320]:
column = 'GarageCars'

In [321]:
df_copy[column].unique()

array([ 1.,  2.,  3.,  0.,  4.,  5., nan])

In [322]:
df_copy[column].fillna(value=0, inplace=True)

In [323]:
df_copy[column].unique()

array([1., 2., 3., 0., 4., 5.])

## Categorize `GarageArea`

* 0->`NA`: No Garage

In [324]:
column = 'GarageArea'

In [325]:
df_copy[column].unique()

array([ 730.,  312.,  482.,  470.,  506.,  440.,  420.,  393.,  525.,
        511.,  264.,  320.,  308.,  751.,  868.,  678.,  958.,  756.,
        484.,  430.,  437.,  400.,  433.,  962.,  880.,  676.,  528.,
        429.,  461.,  762.,  713.,  588.,  480.,  496.,  852.,  592.,
        596.,  535.,  660.,  441.,  490.,  504.,  517.,    0.,  315.,
        576.,  620.,  263.,  318.,  305.,  280.,  240.,  551.,  780.,
        288.,  624.,  363.,  200.,  572.,  180.,  365.,  231.,  450.,
        416.,  591.,  690.,  522.,  467.,  209.,  366., 1017.,  615.,
        580.,  513.,  850.,  621.,  319.,  336.,  352.,  260.,  399.,
        473.,  598.,  531.,  625.,  330.,  741.,  776.,  520.,  686.,
        253.,  286.,  495.,  616.,  275.,  502.,  632.,  390.,  564.,
        396.,  409.,  567.,  529.,  479.,  581.,  565.,  478.,  477.,
        345.,  656.,  754.,  864.,  896.,  834.,  932.,  640.,  927.,
        700.,  583.,  886.,  871.,  949.,  685.,  649.,  539.,  701.,
        392.,  397.,  436.,  434.,  644.,  394.,  658.,  410.,  810.,
        815.,  647.,  623.,  972.,  726.,  844.,  492.,  795.,  984.,
        692.,  782.,  711.,  628.,  845.,  788.,  559.,  542.,  465.,
        612.,  732.,  300.,  252.,  524.,  704.,  561.,  641.,  642.,
        540.,  527.,  784.,  515.,  498.,  768.,  610.,  549.,  368.,
        550.,  530.,  297.,  304.,  350.,  294.,  230.,  246.,  720.,
        281.,  907.,  364.,  384.,  900.,  483.,  162.,  324.,  472.,
        287.,  357.,  207.,  216.,  250., 1184.,  316.,  379.,  220.,
        226.,  668.,  340.,  266.,  462.,  672.,  820., 1138.,  846.,
        904.,  662.,  577.,  608.,  343.,  444., 1231.,  570.,  521.,
        523.,  544.,  195.,  313.,  256.,  215.,  307.,  463.,  295.,
        452.,  501.,  351.,  541.,  885.,  578.,  486.,  920.,  698.,
        898.,  386.,  404.,  460.,  683.,  670.,  557.,  738.,  489.,
       1314.,  787.,  905.,  650.,  706., 1150., 1003.,  789.,  746.,
        870.,  944.,  474.,  428.,  431.,  403.,  516.,  687.,  938.,
        783.,  851.,  627.,  276.,  636.,  545.,  546.,  469.,  512.,
        464.,  267.,  451.,  292.,  301., 1488.,  372.,  401.,  311.,
        299.,  225.,  828.,  869.,  342.,  370.,  160.,  355.,  164.,
        360.,  228.,  270.,  626.,  912.,  249.,  322.,  614.,  534.,
        453., 1348.,  874.,  811.,  438.,  558.,  600.,  532.,  725.,
        715.,  560.,  721.,  814.,  205.,  369.,  599.,  344.,  786.,
        356.,  487.,  185.,  816.,  432.,  666.,  435.,  892.,  499.,
        257.,  398.,  729., 1110.,  556.,  724.,  663.,  481.,  585.,
        488.,  856., 1040.,  878., 1174.,  728.,  843.,  916.,  818.,
        774.,  554.,  876.,  631.,  454.,  388.,  630.,  442.,  925.,
        806.,  758.,  933.,  605., 1092.,  574.,  859.,  575.,  590.,
        594.,  744.,  566.,  283.,  476.,  466.,  552., 1105.,  412.,
        510.,  792.,  310.,  293.,  371., 1200.,  338.,  184.,  374.,
        468.,  331.,  224.,  217.,  408.,  456.,  323.,  638.,  494.,
        303.,  332.,  894.,  796.,  674.,  619.,  747.,  497.,  242.,
        597.,  748.,  622.,  579., 1154.,  509.,  691.,   nan,  100.,
        471.,  571., 1041.,  963.,  423.,  443.,  773.,  618.,  402.,
        675.,  736.,  722.,  582.,  485.,  543.,  831., 1085.,  899.,
        427.,  617.,  959.,  803.,  760.,  928.,  584.,  449.,  688.,
        888.,  326.,  568.,  273.,  234.,  353.,  684.,  791., 1008.,
        648.,  418.,  378.,  258.,  210.,  586.,  836.,  569.,  848.,
        317.,  646.,  555.,  380.,  265.,  609.,  272.,  518.,  714.,
        682.])

In [326]:
df_copy[column].fillna(value=0, inplace=True)

In [327]:
df_copy[column].unique()

array([ 730.,  312.,  482.,  470.,  506.,  440.,  420.,  393.,  525.,
        511.,  264.,  320.,  308.,  751.,  868.,  678.,  958.,  756.,
        484.,  430.,  437.,  400.,  433.,  962.,  880.,  676.,  528.,
        429.,  461.,  762.,  713.,  588.,  480.,  496.,  852.,  592.,
        596.,  535.,  660.,  441.,  490.,  504.,  517.,    0.,  315.,
        576.,  620.,  263.,  318.,  305.,  280.,  240.,  551.,  780.,
        288.,  624.,  363.,  200.,  572.,  180.,  365.,  231.,  450.,
        416.,  591.,  690.,  522.,  467.,  209.,  366., 1017.,  615.,
        580.,  513.,  850.,  621.,  319.,  336.,  352.,  260.,  399.,
        473.,  598.,  531.,  625.,  330.,  741.,  776.,  520.,  686.,
        253.,  286.,  495.,  616.,  275.,  502.,  632.,  390.,  564.,
        396.,  409.,  567.,  529.,  479.,  581.,  565.,  478.,  477.,
        345.,  656.,  754.,  864.,  896.,  834.,  932.,  640.,  927.,
        700.,  583.,  886.,  871.,  949.,  685.,  649.,  539.,  701.,
        392.,  397.,  436.,  434.,  644.,  394.,  658.,  410.,  810.,
        815.,  647.,  623.,  972.,  726.,  844.,  492.,  795.,  984.,
        692.,  782.,  711.,  628.,  845.,  788.,  559.,  542.,  465.,
        612.,  732.,  300.,  252.,  524.,  704.,  561.,  641.,  642.,
        540.,  527.,  784.,  515.,  498.,  768.,  610.,  549.,  368.,
        550.,  530.,  297.,  304.,  350.,  294.,  230.,  246.,  720.,
        281.,  907.,  364.,  384.,  900.,  483.,  162.,  324.,  472.,
        287.,  357.,  207.,  216.,  250., 1184.,  316.,  379.,  220.,
        226.,  668.,  340.,  266.,  462.,  672.,  820., 1138.,  846.,
        904.,  662.,  577.,  608.,  343.,  444., 1231.,  570.,  521.,
        523.,  544.,  195.,  313.,  256.,  215.,  307.,  463.,  295.,
        452.,  501.,  351.,  541.,  885.,  578.,  486.,  920.,  698.,
        898.,  386.,  404.,  460.,  683.,  670.,  557.,  738.,  489.,
       1314.,  787.,  905.,  650.,  706., 1150., 1003.,  789.,  746.,
        870.,  944.,  474.,  428.,  431.,  403.,  516.,  687.,  938.,
        783.,  851.,  627.,  276.,  636.,  545.,  546.,  469.,  512.,
        464.,  267.,  451.,  292.,  301., 1488.,  372.,  401.,  311.,
        299.,  225.,  828.,  869.,  342.,  370.,  160.,  355.,  164.,
        360.,  228.,  270.,  626.,  912.,  249.,  322.,  614.,  534.,
        453., 1348.,  874.,  811.,  438.,  558.,  600.,  532.,  725.,
        715.,  560.,  721.,  814.,  205.,  369.,  599.,  344.,  786.,
        356.,  487.,  185.,  816.,  432.,  666.,  435.,  892.,  499.,
        257.,  398.,  729., 1110.,  556.,  724.,  663.,  481.,  585.,
        488.,  856., 1040.,  878., 1174.,  728.,  843.,  916.,  818.,
        774.,  554.,  876.,  631.,  454.,  388.,  630.,  442.,  925.,
        806.,  758.,  933.,  605., 1092.,  574.,  859.,  575.,  590.,
        594.,  744.,  566.,  283.,  476.,  466.,  552., 1105.,  412.,
        510.,  792.,  310.,  293.,  371., 1200.,  338.,  184.,  374.,
        468.,  331.,  224.,  217.,  408.,  456.,  323.,  638.,  494.,
        303.,  332.,  894.,  796.,  674.,  619.,  747.,  497.,  242.,
        597.,  748.,  622.,  579., 1154.,  509.,  691.,  100.,  471.,
        571., 1041.,  963.,  423.,  443.,  773.,  618.,  402.,  675.,
        736.,  722.,  582.,  485.,  543.,  831., 1085.,  899.,  427.,
        617.,  959.,  803.,  760.,  928.,  584.,  449.,  688.,  888.,
        326.,  568.,  273.,  234.,  353.,  684.,  791., 1008.,  648.,
        418.,  378.,  258.,  210.,  586.,  836.,  569.,  848.,  317.,
        646.,  555.,  380.,  265.,  609.,  272.,  518.,  714.,  682.])

## Exterior1st -> Exterior2nd

## Categorize `Exterior1st`

* 16 ->`NA`: No Garage

In [331]:
column = 'Exterior1st'

In [332]:
df_copy[column].unique()

array([ 1.,  3.,  4.,  8.,  2.,  7.,  6.,  5.,  9., 11., 10., 12., nan,
       15.])

In [333]:
df_copy[column].fillna(value=16, inplace=True)

In [334]:
df_copy[column].unique()

array([ 1.,  3.,  4.,  8.,  2.,  7.,  6.,  5.,  9., 11., 10., 12., 16.,
       15.])

## Categorize `Exterior2nd`

* 16 ->`NA`: No Garage

In [336]:
column = 'Exterior2nd'

In [337]:
df_copy[column].unique()

array([ 1.,  6.,  4.,  5.,  2., 11.,  7., 12.,  3., 10.,  9., 16.,  8.,
       13., nan, 14.])

In [338]:
df_copy[column].fillna(value=16, inplace=True)

In [339]:
df_copy[column].unique()

array([ 1.,  6.,  4.,  5.,  2., 11.,  7., 12.,  3., 10.,  9., 16.,  8.,
       13., 14.])

In [340]:
df_copy.columns[df_copy.isnull().any()].tolist()

[]

In [341]:
df_copy.to_csv('test_impute.csv')